/*******************************************************************************
 * This file is part of SWIFT.
 * Copyright (c) 2016 Matthieu Schaller (schaller@strw.leidenuniv.nl).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/
#ifndef SWIFT_ALIGN_H
#define SWIFT_ALIGN_H

#include "../config.h"

/**
 * @brief The default struct alignment in SWIFT.
 */
/* Moved into config.h */
/* #define SWIFT_STRUCT_ALIGNMENT 32 */

#if SWIFT_STRUCT_ALIGNMENT == -1
/* Use manual, hardcoded particle alignments */


#if defined(SPHENIX_AOS_PARTICLE)

#define SWIFT_STRUCT_ALIGNMENT_PART 32

#elif defined(SPHENIX_SOA_PARTICLE)

#define SWIFT_STRUCT_ALIGNMENT_PART 16
#define SWIFT_STRUCT_ALIGNMENT_PART_ID 8
#define SWIFT_STRUCT_ALIGNMENT_PART_GPART 8
#define SWIFT_STRUCT_ALIGNMENT_PART_X 32
/* #define SWIFT_STRUCT_ALIGNMENT_PART_X 24 */
#define SWIFT_STRUCT_ALIGNMENT_PART_V 16
/* #define SWIFT_STRUCT_ALIGNMENT_PART_V 12 */
#define SWIFT_STRUCT_ALIGNMENT_PART_A_HYDRO 16
/* #define SWIFT_STRUCT_ALIGNMENT_PART_A_HYDRO 12 */
#define SWIFT_STRUCT_ALIGNMENT_PART_MASS 4
#define SWIFT_STRUCT_ALIGNMENT_PART_H 4
#define SWIFT_STRUCT_ALIGNMENT_PART_U 4
#define SWIFT_STRUCT_ALIGNMENT_PART_U_DT 4
#define SWIFT_STRUCT_ALIGNMENT_PART_RHO 4
#define SWIFT_STRUCT_ALIGNMENT_PART_DIV_V 4
#define SWIFT_STRUCT_ALIGNMENT_PART_DIV_V_DT 4
#define SWIFT_STRUCT_ALIGNMENT_PART_DIV_V_PREVIOUS_STEP 4
#define SWIFT_STRUCT_ALIGNMENT_PART_ALPHA_AV 4
#define SWIFT_STRUCT_ALIGNMENT_PART_V_SIG 4
#define SWIFT_STRUCT_ALIGNMENT_PART_LAPLACE_U 4
#define SWIFT_STRUCT_ALIGNMENT_PART_ALPHA_DIFF 4
#define SWIFT_STRUCT_ALIGNMENT_PART_DENSITY1 4
#define SWIFT_STRUCT_ALIGNMENT_PART_FORCE1 4
#define SWIFT_STRUCT_ALIGNMENT_PART_DENSITY2 4
#define SWIFT_STRUCT_ALIGNMENT_PART_FORCE2 4
#define SWIFT_STRUCT_ALIGNMENT_PART_DENSITY3 4
#define SWIFT_STRUCT_ALIGNMENT_PART_FORCE3 4
#define SWIFT_STRUCT_ALIGNMENT_PART_DENSITY4 16
/* #define SWIFT_STRUCT_ALIGNMENT_PART_DENSITY4 12 */
#define SWIFT_STRUCT_ALIGNMENT_PART_FORCE4 4
#define SWIFT_STRUCT_ALIGNMENT_PART_FORCE5 4
#define SWIFT_STRUCT_ALIGNMENT_PART_FORCE6 4
#define SWIFT_STRUCT_ALIGNMENT_PART_ADDITIONAL_STRUCTS 1
#define SWIFT_STRUCT_ALIGNMENT_PART_RT_TIME_DATA 8
#define SWIFT_STRUCT_ALIGNMENT_PART_DEPTH_H 1
#define SWIFT_STRUCT_ALIGNMENT_PART_TIME_BIN 1
/* #define SWIFT_STRUCT_ALIGNMENT_PART_LIMITER_DATA 3 */
#define SWIFT_STRUCT_ALIGNMENT_PART_LIMITER_DATA 4
#define SWIFT_STRUCT_ALIGNMENT_PART_TI_DRIFT 4
#define SWIFT_STRUCT_ALIGNMENT_PART_TI_KICK 4
#define SWIFT_STRUCT_ALIGNMENT_PART_DEBUGGING 16


#elif defined(SPHENIX_UPSTREAM_PARTICLE)

#define SWIFT_STRUCT_ALIGNMENT_PART 32

#elif defined(SPHENIX_RANDOM_ORDER_PARTICLE)

#define SWIFT_STRUCT_ALIGNMENT_PART 32


#elif defined(SPHENIX_PACK_GRADIENT_PARTICLE)

#define SWIFT_STRUCT_ALIGNMENT_PART 16
#define SWIFT_STRUCT_ALIGNMENT_X_H_V_M 64
/* #define SWIFT_STRUCT_ALIGNMENT_X_H_V_M 44 */
#define SWIFT_STRUCT_ALIGNMENT_GRADIENT_PACK 32
/* #define SWIFT_STRUCT_ALIGNMENT_GRADIENT_PACK 28 */
#define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK 32
/* #define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK 20 */
#define SWIFT_STRUCT_ALIGNMENT_DENSITY_UNPACK 32
/* #define SWIFT_STRUCT_ALIGNMENT_DENSITY_UNPACK 28 */
#define SWIFT_STRUCT_ALIGNMENT_FORCE_UNPACK 32
/* #define SWIFT_STRUCT_ALIGNMENT_FORCE_UNPACK 20 */
#define SWIFT_STRUCT_ALIGNMENT_OTHERS 32


#elif defined(SPHENIX_PACK_FORCE_TYPE_PARTICLE)

#define SWIFT_STRUCT_ALIGNMENT_PART 16
#define SWIFT_STRUCT_ALIGNMENT_X_H_V_M_DOUBLE 32
/* #define SWIFT_STRUCT_ALIGNMENT_X_H_V_M_DOUBLE 24 */
#define SWIFT_STRUCT_ALIGNMENT_X_H_V_M 32
/* #define SWIFT_STRUCT_ALIGNMENT_X_H_V_M 20 */
#define SWIFT_STRUCT_ALIGNMENT_GRADIENT_PACK 16
/* #define SWIFT_STRUCT_ALIGNMENT_GRADIENT_PACK 12 */
#define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK 32
#define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK_TIMEBIN 4
#define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK_LIMITER 16
/* #define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK_LIMITER 12 */
#define SWIFT_STRUCT_ALIGNMENT_DENSITY_UNPACK 32
/* #define SWIFT_STRUCT_ALIGNMENT_DENSITY_UNPACK 28 */
#define SWIFT_STRUCT_ALIGNMENT_FORCE_UNPACK 32
/* #define SWIFT_STRUCT_ALIGNMENT_FORCE_UNPACK 20 */
#define SWIFT_STRUCT_ALIGNMENT_OTHERS 32

#elif defined(SPHENIX_PACK_FORCE_PARTICLE)

#define SWIFT_STRUCT_ALIGNMENT_PART 16
#define SWIFT_STRUCT_ALIGNMENT_X_H_V_M 64
/* #define SWIFT_STRUCT_ALIGNMENT_X_H_V_M 44 */
#define SWIFT_STRUCT_ALIGNMENT_GRADIENT_PACK 16
/* #define SWIFT_STRUCT_ALIGNMENT_GRADIENT_PACK 12 */
#define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK 64
/* #define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK 36 */
#define SWIFT_STRUCT_ALIGNMENT_DENSITY_UNPACK 32
/* #define SWIFT_STRUCT_ALIGNMENT_DENSITY_UNPACK 28 */
#define SWIFT_STRUCT_ALIGNMENT_FORCE_UNPACK 32
/* #define SWIFT_STRUCT_ALIGNMENT_FORCE_UNPACK 20 */
#define SWIFT_STRUCT_ALIGNMENT_OTHERS 32


#elif defined(SPHENIX_PACK_SHARED_PARTICLE)

#define SWIFT_STRUCT_ALIGNMENT_PART 16
#define SWIFT_STRUCT_ALIGNMENT_X_H_V_M 64
/* #define SWIFT_STRUCT_ALIGNMENT_X_H_V_M 44 */
#define SWIFT_STRUCT_ALIGNMENT_GRADIENT_PACK 16
/* #define SWIFT_STRUCT_ALIGNMENT_GRADIENT_PACK 12 */
#define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK 32
/* #define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK 20 */
#define SWIFT_STRUCT_ALIGNMENT_FORCE_GRADIENT_PACK_SHARED 16
#define SWIFT_STRUCT_ALIGNMENT_DENSITY_UNPACK 32
/* #define SWIFT_STRUCT_ALIGNMENT_DENSITY_UNPACK 28 */
#define SWIFT_STRUCT_ALIGNMENT_FORCE_UNPACK 32
/* #define SWIFT_STRUCT_ALIGNMENT_FORCE_UNPACK 20 */
#define SWIFT_STRUCT_ALIGNMENT_OTHERS 32

#else
#error "Unknown memory layout realisation"
#endif /* particle memory layout branch */

#else /* if SWIFT_STRUCT_ALIGNMENT == -1 */
/* All of them use the same alignment: SWIFT_STRUCT_ALIGNMENT */

#define SWIFT_STRUCT_ALIGNMENT_PART SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_X_H_V_M SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_X_H_V_M_DOUBLE SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_GRADIENT_PACK SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK_TIMEBIN SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_FORCE_PACK_LIMITER SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_DENSITY_UNPACK SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_FORCE_UNPACK SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_OTHERS SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_FORCE_GRADIENT_PACK_SHARED SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_ID SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_GPART SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_X SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_V SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_A_HYDRO SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_MASS SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_H SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_U SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_U_DT SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_RHO SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_DIV_V SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_DIV_V_DT SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_DIV_V_PREVIOUS_STEP
#define SWIFT_STRUCT_ALIGNMENT_PART_ALPHA_AV SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_V_SIG SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_LAPLACE_U SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_ALPHA_DIFF SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_DENSITY1 SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_FORCE1 SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_DENSITY2 SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_FORCE2 SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_DENSITY3 SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_FORCE3 SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_DENSITY4 SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_FORCE4 SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_FORCE5 SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_FORCE6 SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_ADDITIONAL_STRUCTS SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_RT_TIME_DATA SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_DEPTH_H SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_TIME_BIN SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_LIMITER_DATA SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_TI_DRIFT SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_TI_KICK SWIFT_STRUCT_ALIGNMENT
#define SWIFT_STRUCT_ALIGNMENT_PART_DEBUGGING SWIFT_STRUCT_ALIGNMENT

#endif


#ifdef PACKED_STRUCTS
/* Make structs packed as well */

#define SWIFT_STRUCT_ALIGN __attribute__((packed, aligned(32)))
#define SWIFT_STRUCT_GPU_PART_SEND_G_ALIGN __attribute__((packed, aligned(128)))
#define SWIFT_STRUCT_GPU_PART_RECV_G_ALIGN __attribute__((packed, aligned(16)))
#define SWIFT_STRUCT_GPU_PART_SEND_F_ALIGN __attribute__((packed, aligned(128)))
#define SWIFT_STRUCT_GPU_PART_RECV_F_ALIGN __attribute__((packed, aligned(32)))
#define SWIFT_STRUCT_ALIGN_PART \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART)))

#if defined(SPHENIX_PACK_GRADIENT_PARTICLE) ||   \
    defined(SPHENIX_PACK_FORCE_PARTICLE) ||      \
    defined(SPHENIX_PACK_FORCE_TYPE_PARTICLE) || \
    defined(SPHENIX_PACK_SHARED_PARTICLE)
#define SWIFT_STRUCT_ALIGN_X_H_V_M \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_X_H_V_M)))
#define SWIFT_STRUCT_ALIGN_GRADIENT_PACK \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_GRADIENT_PACK)))
#define SWIFT_STRUCT_ALIGN_FORCE_PACK \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_FORCE_PACK)))
#define SWIFT_STRUCT_ALIGN_DENSITY_UNPACK \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_DENSITY_UNPACK)))
#define SWIFT_STRUCT_ALIGN_FORCE_UNPACK \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_FORCE_UNPACK)))
#define SWIFT_STRUCT_ALIGN_OTHERS \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_OTHERS)))

#if defined(SPHENIX_PACK_FORCE_TYPE_PARTICLE)
  /* Additions for PACK_FORCE_TYPE */

#define SWIFT_STRUCT_ALIGN_X_H_V_M_DOUBLE \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_X_H_V_M_DOUBLE)))
#define SWIFT_STRUCT_ALIGN_FORCE_PACK_TIMEBIN \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_FORCE_PACK_TIMEBIN)))
#define SWIFT_STRUCT_ALIGN_FORCE_PACK_LIMITER \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_FORCE_PACK_LIMITER)))
#define SWIFT_STRUCT_ALIGN_FORCE_PACK \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_FORCE_PACK)))

#endif /* defined SPHENIX_PACK_FORCE_TYPE_PARTICLE */

#endif /* defined SPHENIX_PACK_*_PARTICLE */

#if defined(SPHENIX_PACK_SHARED_PARTICLE)
#define SWIFT_STRUCT_ALIGN_FORCE_GRADIENT_PACK_SHARED \
  __attribute__((packed,                              \
                 aligned(SWIFT_STRUCT_ALIGNMENT_FORCE_GRADIENT_PACK_SHARED)))
#endif

#if defined(SPHENIX_SOA_PARTICLE)
#define SWIFT_STRUCT_ALIGN_PART_ID \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_ID)))
#define SWIFT_STRUCT_ALIGN_PART_GPART \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_GPART)))
#define SWIFT_STRUCT_ALIGN_PART_X \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_X)))
#define SWIFT_STRUCT_ALIGN_PART_V \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_V)))
#define SWIFT_STRUCT_ALIGN_PART_A_HYDRO \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_A_HYDRO)))
#define SWIFT_STRUCT_ALIGN_PART_MASS \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_MASS)))
#define SWIFT_STRUCT_ALIGN_PART_H \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_H)))
#define SWIFT_STRUCT_ALIGN_PART_U \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_U)))
#define SWIFT_STRUCT_ALIGN_PART_U_DT \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_U_DT)))
#define SWIFT_STRUCT_ALIGN_PART_RHO \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_RHO)))
#define SWIFT_STRUCT_ALIGN_PART_DIV_V \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_DIV_V)))
#define SWIFT_STRUCT_ALIGN_PART_DIV_V_DT \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_DIV_V_DT)))
#define SWIFT_STRUCT_ALIGN_PART_DIV_V_PREVIOUS_STEP \
  __attribute__((packed,                            \
                 aligned(SWIFT_STRUCT_ALIGNMENT_PART_DIV_V_PREVIOUS_STEP)))
#define SWIFT_STRUCT_ALIGN_PART_ALPHA_AV \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_ALPHA_AV)))
#define SWIFT_STRUCT_ALIGN_PART_V_SIG \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_V_SIG)))
#define SWIFT_STRUCT_ALIGN_PART_LAPLACE_U \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_LAPLACE_U)))
#define SWIFT_STRUCT_ALIGN_PART_ALPHA_DIFF \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_ALPHA_DIFF)))
#define SWIFT_STRUCT_ALIGN_PART_DENSITY1 \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_DENSITY1)))
#define SWIFT_STRUCT_ALIGN_PART_FORCE1 \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_FORCE1)))
#define SWIFT_STRUCT_ALIGN_PART_DENSITY2 \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_DENSITY2)))
#define SWIFT_STRUCT_ALIGN_PART_FORCE2 \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_FORCE2)))
#define SWIFT_STRUCT_ALIGN_PART_DENSITY3 \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_DENSITY3)))
#define SWIFT_STRUCT_ALIGN_PART_FORCE3 \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_FORCE3)))
#define SWIFT_STRUCT_ALIGN_PART_DENSITY4 \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_DENSITY4)))
#define SWIFT_STRUCT_ALIGN_PART_FORCE4 \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_FORCE4)))
#define SWIFT_STRUCT_ALIGN_PART_FORCE5 \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_FORCE5)))
#define SWIFT_STRUCT_ALIGN_PART_FORCE6 \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_FORCE6)))
#define SWIFT_STRUCT_ALIGN_PART_ADDITIONAL_STRUCTS \
  __attribute__((packed,                           \
                 aligned(SWIFT_STRUCT_ALIGNMENT_PART_ADDITIONAL_STRUCTS)))
#define SWIFT_STRUCT_ALIGN_PART_RT_TIME_DATA \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_RT_TIME_DATA)))
#define SWIFT_STRUCT_ALIGN_PART_DEPTH_H \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_DEPTH_H)))
#define SWIFT_STRUCT_ALIGN_PART_TIME_BIN \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_TIME_BIN)))
#define SWIFT_STRUCT_ALIGN_PART_LIMITER_DATA \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_LIMITER_DATA)))
#define SWIFT_STRUCT_ALIGN_PART_TI_DRIFT \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_TI_DRIFT)))
#define SWIFT_STRUCT_ALIGN_PART_TI_KICK \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_TI_KICK)))
#define SWIFT_STRUCT_ALIGN_PART_DEBUGGING \
  __attribute__((packed, aligned(SWIFT_STRUCT_ALIGNMENT_PART_DEBUGGING)))
#endif /* if defined (SPHENIX_SOA_PARTICLE) */

#else /* PACKED_STRUCTS not defined */

#define SWIFT_STRUCT_ALIGN __attribute__((aligned(32)))
#define SWIFT_STRUCT_GPU_PART_SEND_G_ALIGN __attribute__((aligned(128)))
#define SWIFT_STRUCT_GPU_PART_RECV_G_ALIGN __attribute__((aligned(16)))
#define SWIFT_STRUCT_GPU_PART_SEND_F_ALIGN __attribute__((aligned(128)))
#define SWIFT_STRUCT_GPU_PART_RECV_F_ALIGN __attribute__((aligned(32)))
#define SWIFT_STRUCT_ALIGN_PART \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART)))

#if defined(SPHENIX_PACK_GRADIENT_PARTICLE) || \
    defined(SPHENIX_PACK_FORCE_PARTICLE) ||    \
    defined(SPHENIX_PACK_SHARED_PARTICLE)
#define SWIFT_STRUCT_ALIGN_X_H_V_M \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_X_H_V_M)))
#define SWIFT_STRUCT_ALIGN_GRADIENT_PACK \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_GRADIENT_PACK)))
#define SWIFT_STRUCT_ALIGN_FORCE_PACK \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_FORCE_PACK)))
#define SWIFT_STRUCT_ALIGN_DENSITY_UNPACK \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_DENSITY_UNPACK)))
#define SWIFT_STRUCT_ALIGN_FORCE_UNPACK \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_FORCE_UNPACK)))
#define SWIFT_STRUCT_ALIGN_OTHERS \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_OTHERS)))
#endif

#if defined(SPHENIX_PACK_SHARED_PARTICLE)
#define SWIFT_STRUCT_ALIGN_FORCE_GRADIENT_PACK_SHARED \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_FORCE_GRADIENT_PACK_SHARED)))
#endif

#if defined(SPHENIX_SOA_PARTICLE)
#define SWIFT_STRUCT_ALIGN_PART_ID \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_ID)))
#define SWIFT_STRUCT_ALIGN_PART_GPART \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_GPART)))
#define SWIFT_STRUCT_ALIGN_PART_X \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_X)))
#define SWIFT_STRUCT_ALIGN_PART_V \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_V)))
#define SWIFT_STRUCT_ALIGN_PART_A_HYDRO \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_A_HYDRO)))
#define SWIFT_STRUCT_ALIGN_PART_MASS \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_MASS)))
#define SWIFT_STRUCT_ALIGN_PART_H \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_H)))
#define SWIFT_STRUCT_ALIGN_PART_U \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_U)))
#define SWIFT_STRUCT_ALIGN_PART_U_DT \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_U_DT)))
#define SWIFT_STRUCT_ALIGN_PART_RHO \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_RHO)))
#define SWIFT_STRUCT_ALIGN_PART_DIV_V \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_DIV_V)))
#define SWIFT_STRUCT_ALIGN_PART_DIV_V_DT \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_DIV_V_DT)))
#define SWIFT_STRUCT_ALIGN_PART_DIV_V_PREVIOUS_STEP \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_DIV_V_PREVIOUS_STEP)))
#define SWIFT_STRUCT_ALIGN_PART_ALPHA_AV \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_ALPHA_AV)))
#define SWIFT_STRUCT_ALIGN_PART_V_SIG \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_V_SIG)))
#define SWIFT_STRUCT_ALIGN_PART_LAPLACE_U \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_LAPLACE_U)))
#define SWIFT_STRUCT_ALIGN_PART_ALPHA_DIFF \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_ALPHA_DIFF)))
#define SWIFT_STRUCT_ALIGN_PART_DENSITY1 \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_DENSITY1)))
#define SWIFT_STRUCT_ALIGN_PART_FORCE1 \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_FORCE1)))
#define SWIFT_STRUCT_ALIGN_PART_DENSITY2 \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_DENSITY2)))
#define SWIFT_STRUCT_ALIGN_PART_FORCE2 \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_FORCE2)))
#define SWIFT_STRUCT_ALIGN_PART_DENSITY3 \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_DENSITY3)))
#define SWIFT_STRUCT_ALIGN_PART_FORCE3 \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_FORCE3)))
#define SWIFT_STRUCT_ALIGN_PART_DENSITY4 \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_DENSITY4)))
#define SWIFT_STRUCT_ALIGN_PART_FORCE4 \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_FORCE4)))
#define SWIFT_STRUCT_ALIGN_PART_FORCE5 \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_FORCE5)))
#define SWIFT_STRUCT_ALIGN_PART_FORCE6 \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_FORCE6)))
#define SWIFT_STRUCT_ALIGN_PART_ADDITIONAL_STRUCTS \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_ADDITIONAL_STRUCTS)))
#define SWIFT_STRUCT_ALIGN_PART_RT_TIME_DATA \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_RT_TIME_DATA)))
#define SWIFT_STRUCT_ALIGN_PART_DEPTH_H \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_DEPTH_H)))
#define SWIFT_STRUCT_ALIGN_PART_TIME_BIN \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_TIME_BIN)))
#define SWIFT_STRUCT_ALIGN_PART_LIMITER_DATA \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_LIMITER_DATA)))
#define SWIFT_STRUCT_ALIGN_PART_TI_DRIFT \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_TI_DRIFT)))
#define SWIFT_STRUCT_ALIGN_PART_TI_KICK \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_TI_KICK)))
#define SWIFT_STRUCT_ALIGN_PART_DEBUGGING \
  __attribute__((aligned(SWIFT_STRUCT_ALIGNMENT_PART_DEBUGGING)))
#endif /* if defined (SPHENIX_SOA_PARTICLE) */

#endif /* if defined(PACKED_STRUCTS) */


/**
 * @brief The default cache alignment in SWIFT.
 */
#define SWIFT_CACHE_ALIGNMENT 64

/**
 * @brief Defines alignment of caches
 */
#define SWIFT_CACHE_ALIGN __attribute__((aligned(SWIFT_CACHE_ALIGNMENT)))

/**
 * @brief Macro to tell the compiler that a given array has the specified
 * alignment.
 *
 * Note that this turns into a no-op but gives information to the compiler.
 * For GCC versions older than 4.6 this is ignored as the builtin does not
 * exist.
 *
 * @param type The type of the array.
 * @param array The array.
 * @param alignment The alignment in bytes of the array.
 */
#if defined(__ICC)
#define swift_align_information(type, array, alignment) \
  __assume_aligned(array, alignment);
#elif (__GNUC__ > 4) || (__GNUC__ == 4 && __GNUC_MINOR__ > 6)
#define swift_align_information(type, array, alignment) \
  array = (type*)__builtin_assume_aligned(array, alignment);
#else
#define swift_align_information(type, array, alignment) ;
#endif

/**
 * @brief Macro to create a restrict pointer to an array and tell the compiler
 * that the given array has the specified
 * alignment.
 *
 * Note that this turns into a no-op but gives information to the compiler.
 *
 * @param array The array.
 * @param ptr Pointer to array
 * @param type Type of array
 * @param alignment The alignment in bytes of the array.
 */
#define swift_declare_aligned_ptr(type, array, ptr, alignment) \
  type* restrict array = ptr;                                  \
  swift_align_information(type, array, alignment);

/**
 * @brief Macro to tell the compiler that a given number is 0 modulo a given
 * size.
 *
 * Note that this turns into a no-op but gives information to the compiler.
 * GCC does not have the equivalent built-in so defaults to nothing.
 *
 * @param var The variable
 * @param size The modulo of interest.
 */
#if defined(__ICC)
#define swift_assume_size(var, size) __assume(var % size == 0);
#else
#define swift_assume_size(var, size) ;
#endif

#endif /* SWIFT_ALIGN_H */
