#pragma once

#include "error.h"
#include "hydro_part_generated.h"
#include "inline.h"
#include "parameters.h"

#include <stdlib.h>

/**
 * Struct holding handles to all particle data arrays
 * TODO: To be generated by python
 */
struct part_arrays {
  struct part* p;

#ifdef SWIFT_DEBUG_CHECKS
  int nr_parts;
#endif
};


/**
 * Initialize particle data array(s).
 * TODO: To be generated by python
 */
static __attribute__((always_inline)) INLINE void init_parts(
    struct part_arrays* data, const struct parameters* params) {

  data->p = (struct part*)calloc(params->nr_parts, sizeof(struct part));

#ifdef SWIFT_DEBUG_CHECKS
  data->nr_parts = params->nr_parts;
#endif

  message("size of part is %lu bytes", sizeof(struct part));
  message("size of alloc'd parts is %.3g Mb",
          (params->nr_parts * sizeof(struct part)) / (1024. * 1024.));
}


/**
 * Free the bytes from their prison of labour.
 * TODO: To be generated by python
 */
static __attribute__((always_inline)) INLINE void clear_parts(
    struct part_arrays* data) {
  free(data->p);
}
