/**
  * WARNING: THIS FILE WAS GENERATED. MODIFICATIONS WILL NOT STICK.
  * File template is /home/mivkov/Durham/swiftgpupacksim/py/templates/hydro_part_arrays_flush.h.jinja.template
  */
#pragma once

#include "flush_caches_x86.h"
#include "hydro_part.h"




#ifdef SWIFT_CACHE_FLUSH_X86
/**
 * @brief flushes all particle data from caches.
 *
 * @param part_data: Array containing all particle data
 * @param nr_parts: Number of particles in part_data array.
 */
__attribute__((always_inline)) INLINE static void hydro_part_arrays_flush_from_cache(
  struct hydro_part_arrays* part_data, size_t nr_parts) {


	size_t len_part = nr_parts / sizeof(struct part) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part, len_part);



  flush_cache_x86_fence();
}
#endif


