/**
  * WARNING: THIS FILE WAS GENERATED. MODIFICATIONS WILL NOT STICK.
  * File template is /home/mivkov/Durham/swiftgpupacksim/py/templates/hydro_part_arrays_struct.h.jinja.template
  */
#pragma once



/* Forward declare all part structs */

struct part;

/**
 * Struct holding handles to all particle data arrays
 */
struct hydro_part_arrays {
 
  struct part *_part;

#ifdef SWIFT_DEBUG_CHECKS
  int nr_parts;
#endif
};

