/**
  * WARNING: THIS FILE WAS GENERATED. MODIFICATIONS WILL NOT STICK.
  * File template is /home/mivkov/Durham/swiftgpupacksim/py/templates/hydro_part_arrays_flush.h.jinja.template
  */
#pragma once

#include "flush_caches_x86.h"
#include "hydro_part.h"




#ifdef SWIFT_CACHE_FLUSH_X86
/**
 * @brief flushes all particle data from caches.
 * 
 * @param part_data: Array containing all particle data
 * @param nr_parts: Number of particles in part_data array.
 */
__attribute__((always_inline)) INLINE void hydro_part_arrays_flush_from_cache(
  struct hydro_part_arrays* part_data, size_t nr_parts) {


	size_t len_part = nr_parts / sizeof(struct part) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part, len_part);


	size_t len_x_h_v_m = nr_parts / sizeof(struct x_h_v_m) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_x_h_v_m, len_x_h_v_m);


	size_t len_gradient_pack = nr_parts / sizeof(struct gradient_pack) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_gradient_pack, len_gradient_pack);


	size_t len_force_pack = nr_parts / sizeof(struct force_pack) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_force_pack, len_force_pack);


	size_t len_force_gradient_pack_shared = nr_parts / sizeof(struct force_gradient_pack_shared) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_force_gradient_pack_shared, len_force_gradient_pack_shared);


	size_t len_density_unpack = nr_parts / sizeof(struct density_unpack) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_density_unpack, len_density_unpack);


	size_t len_force_unpack = nr_parts / sizeof(struct force_unpack) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_force_unpack, len_force_unpack);


	size_t len_others = nr_parts / sizeof(struct others) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_others, len_others);



  flush_cache_x86_fence();
}
#endif


