/**
  * WARNING: THIS FILE WAS GENERATED. MODIFICATIONS WILL NOT STICK.
  * File template is /home/mivkov/Durham/swiftgpupacksim/py/templates/parts.h.jinja.template
  */
#pragma once



#include "hydro_part.h"
#include "hydro_part_arrays_struct.h"

#include "swift_placeholders/error.h"
#include "swift_placeholders/inline.h"
#include "swift_placeholders/memuse.h"

#include <string.h> /* for memset() */



/**
 * Allocate particle data array(s).
 */
static __attribute__((always_inline)) INLINE void init_part_arrays(struct hydro_part_arrays* parr, int nr_parts) {

  if (swift_memalign("parts_part", (void**)&parr->_part, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part, 0, nr_parts * sizeof(struct part));


#ifdef SWIFT_DEBUG_CHECKS
  parr->nr_parts = nr_parts;
#endif
  /* We're done. Print out some information to screen */
  size_t total = 0;
  total+=sizeof(struct part);

  message("total size of a particle is %lu bytes", total);
  message("size of alloc'd parts is %.3g Mb", (nr_parts * total) / (1024. * 1024.));
}

/**
 * @brief Free the bytes from their prison of labour.
 */
static __attribute__((always_inline)) INLINE void clear_parts(struct hydro_part_arrays* parr) {

  free(parr->_part);
}

/**
 * @brief Initialise a hydro_part_arrays struct `dest` as an offset of a different
 * hydro_part_arrays struct `src`. Intended to initilise cell particle array data
 * as offsets to the global particle array.
 */
__attribute__((always_inline)) INLINE static void part_arrays_set_pointer_offset(
  struct hydro_part_arrays* dest, const struct hydro_part_arrays* src, ptrdiff_t offset
  ){


  dest->_part = &src->_part[offset];
}


