/**
  * WARNING: THIS FILE WAS GENERATED. MODIFICATIONS WILL NOT STICK.
  * File template is /home/mivkov/Durham/swiftgpupacksim/py/templates/hydro_part_arrays_struct.h.jinja.template
  */
#pragma once



/* Forward declare all part structs */

struct part;
struct x_h_v_m;
struct gradient_pack;
struct force_pack;
struct density_unpack;
struct force_unpack;
struct others;

/**
 * Struct holding handles to all particle data arrays
 */
struct hydro_part_arrays {
 
  struct part *_part;
 
  struct x_h_v_m *_x_h_v_m;
 
  struct gradient_pack *_gradient_pack;
 
  struct force_pack *_force_pack;
 
  struct density_unpack *_density_unpack;
 
  struct force_unpack *_force_unpack;
 
  struct others *_others;

#ifdef SWIFT_DEBUG_CHECKS
  int nr_parts;
#endif
};

