/**
  * WARNING: THIS FILE WAS GENERATED. MODIFICATIONS WILL NOT STICK.
  * File template is /home/mivkov/Durham/swiftgpupacksim/py/templates/parts.h.jinja.template
  */
#pragma once



#include "hydro_part.h"
#include "hydro_part_arrays_struct.h"

#include "swift_placeholders/error.h"
#include "swift_placeholders/inline.h"
#include "swift_placeholders/memuse.h"

#include <string.h> /* for memset() */



/**
 * Allocate particle data array(s).
 */
static __attribute__((always_inline)) INLINE void init_part_arrays(struct hydro_part_arrays* parr, int nr_parts) {

  if (swift_memalign("parts_part", (void**)&parr->_part, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part, 0, nr_parts * sizeof(struct part));

  if (swift_memalign("parts_x_h_v_m", (void**)&parr->_x_h_v_m, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct x_h_v_m)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_x_h_v_m, 0, nr_parts * sizeof(struct x_h_v_m));

  if (swift_memalign("parts_gradient_pack", (void**)&parr->_gradient_pack, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct gradient_pack)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_gradient_pack, 0, nr_parts * sizeof(struct gradient_pack));

  if (swift_memalign("parts_force_pack", (void**)&parr->_force_pack, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct force_pack)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_force_pack, 0, nr_parts * sizeof(struct force_pack));

  if (swift_memalign("parts_density_unpack", (void**)&parr->_density_unpack, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct density_unpack)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_density_unpack, 0, nr_parts * sizeof(struct density_unpack));

  if (swift_memalign("parts_force_unpack", (void**)&parr->_force_unpack, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct force_unpack)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_force_unpack, 0, nr_parts * sizeof(struct force_unpack));

  if (swift_memalign("parts_others", (void**)&parr->_others, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct others)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_others, 0, nr_parts * sizeof(struct others));


#ifdef SWIFT_DEBUG_CHECKS
  parr->nr_parts = nr_parts;
#endif

#ifdef SWIFT_DEBUG_CHECKS
  /* Give all particles a unique debugging ID which will be used to verify that
   * we're accessing the correct split struct. Note: ID = 0 is forbidden! */
  for (long long i = 1; i <= nr_parts; i++) {

    parr->_part[i-1]._accessor_id = i;
    parr->_x_h_v_m[i-1]._accessor_id = i;
    parr->_gradient_pack[i-1]._accessor_id = i;
    parr->_force_pack[i-1]._accessor_id = i;
    parr->_density_unpack[i-1]._accessor_id = i;
    parr->_force_unpack[i-1]._accessor_id = i;
    parr->_others[i-1]._accessor_id = i;
  }
#endif
  /* We're done. Print out some information to screen */
  size_t total = 0;
  total+=sizeof(struct part);
  total+=sizeof(struct x_h_v_m);
  total+=sizeof(struct gradient_pack);
  total+=sizeof(struct force_pack);
  total+=sizeof(struct density_unpack);
  total+=sizeof(struct force_unpack);
  total+=sizeof(struct others);

  message("total size of a particle is %lu bytes", total);
  message("size of alloc'd parts is %.3g Mb", (nr_parts * total) / (1024. * 1024.));
}

/**
 * @brief Free the bytes from their prison of labour.
 */
static __attribute__((always_inline)) INLINE void clear_parts(struct hydro_part_arrays* parr) {

  free(parr->_part);
  free(parr->_x_h_v_m);
  free(parr->_gradient_pack);
  free(parr->_force_pack);
  free(parr->_density_unpack);
  free(parr->_force_unpack);
  free(parr->_others);
}

/**
 * @brief Initialise a hydro_part_arrays struct `dest` as an offset of a different
 * hydro_part_arrays struct `src`. Intended to initilise cell particle array data
 * as offsets to the global particle array.
 */
__attribute__((always_inline)) INLINE static void part_arrays_set_pointer_offset(
  struct hydro_part_arrays* dest, const struct hydro_part_arrays* src, ptrdiff_t offset
  ){


  dest->_part = &src->_part[offset];
  dest->_x_h_v_m = &src->_x_h_v_m[offset];
  dest->_gradient_pack = &src->_gradient_pack[offset];
  dest->_force_pack = &src->_force_pack[offset];
  dest->_density_unpack = &src->_density_unpack[offset];
  dest->_force_unpack = &src->_force_unpack[offset];
  dest->_others = &src->_others[offset];
}


