
#ifndef SWIFT_HYDRO_PART_NO_FLAVOUR_SPECIFIED_H
#define SWIFT_HYDRO_PART_NO_FLAVOUR_SPECIFIED_H
/**
  * WARNING: THIS FILE WAS GENERATED. MODIFICATIONS WILL NOT STICK.
  * File template is /home/mivkov/Durham/swiftgpupacksim/py/templates/test_hydro_part.h.jinja.template
  */
/*******************************************************************************
 * Copyright (c) NO AUTHORS SPECIFIED
 ******************************************************************************/

  




#ifndef USE_PART_STRUCT_ACCESSORS
#error "USE_PART_STRUCT_ACCESSORS macro not defined. This won't compile."
#endif

#include <float.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>

#include "hydro_part_arrays_struct.h"


  
#include "align.h"
#include "error.h"
#include "hydro_part_placeholder_structs.h"
#include "hydro_part_arrays_struct.h"
#include "rt_struct.h"
#include "timestep_limiter_struct.h"
#include <float.h>
#include <limits.h>
#include <stddef.h>



/* Some definitions and declarations to make the test programs compile */
#ifndef MY_ARRAY_SIZE
#define MY_ARRAY_SIZE 4
#endif

#define NDIM1 2
#define NDIM2 3
#define NDIM3 4

#define INLINE inline
#define DEBUG
typedef long long integertime_t;
typedef int8_t timebin_t;

enum color {
  red = 0,
  green,
  blue,
  purple,
  white,
  black
  };

struct my_struct{};
struct gpart{
  double x[3];
  float m;
};





struct part {

#ifdef USE_PART_STRUCT_ACCESSORS
  /*! offset/index of particle in cell particle data array */
  size_t _cell_offset;
#endif

#ifdef USE_PART_STRUCT_ACCESSORS
  /*! pointer to particle data array struct of the cell this particle is located in */
  struct part_arrays* _cell_part_arrays;
#endif

  /*! my integer */
  int _my_int_arr[4];

  /*! my long */
  long _my_long_arr[4];

  /*! my long long */
  long long _my_longlong_arr[4];

  /*! my float */
  float _my_float_arr[4];

  /*! my double */
  double _my_dble_arr[4];

  /*! my_char */
  char _my_char_arr[4];

  /*! my integertime */
  integertime_t _my_integertime_arr[4];

  /*! my timebin */
  timebin_t _my_timebin_arr[4];

  /*! some externally defined struct */
  struct my_struct _my_external_struct_arr[4];

#ifdef SWIFT_DEBUG_CHECKS
  /*! This particle's accessor ID, identical for all structs associated with this particle. */
  long long _accessor_id;
#endif

};

struct part2 {

  /*! my integer */
  int _my_int_arr2[4];

  /*! my long */
  long _my_long_arr2[4];

  /*! my long long */
  long long _my_longlong_arr2[4];

  /*! my float */
  float _my_float_arr2[4];

  /*! my double */
  double _my_dble_arr2[4];

  /*! my_char */
  char _my_char_arr2[4];

  /*! my integertime */
  integertime_t _my_integertime_arr2[4];

  /*! my timebin */
  timebin_t _my_timebin_arr2[4];

  /*! some externally defined struct */
  struct my_struct _my_external_struct_arr2[4];

#ifdef SWIFT_DEBUG_CHECKS
  /*! This particle's accessor ID, identical for all structs associated with this particle. */
  long long _accessor_id;
#endif

};

struct part3 {

#ifdef DEBUG
  /*! my integer */
  int _my_int_arr3[4];
#endif

#ifdef DEBUG
  /*! my long */
  long _my_long_arr3[4];
#endif

#ifdef DEBUG
  /*! my long long */
  long long _my_longlong_arr3[4];
#endif

#ifdef DEBUG
  /*! my float */
  float _my_float_arr3[4];
#endif

#ifdef DEBUG
  /*! my double */
  double _my_dble_arr3[4];
#endif

#ifdef DEBUG
  /*! my_char */
  char _my_char_arr3[4];
#endif

#ifdef DEBUG
  /*! my integertime */
  integertime_t _my_integertime_arr3[4];
#endif

#ifdef DEBUG
  /*! my timebin */
  timebin_t _my_timebin_arr3[4];
#endif

#ifdef SWIFT_DEBUG_CHECKS
  /*! This particle's accessor ID, identical for all structs associated with this particle. */
  long long _accessor_id;
#endif

};


/**
 * @brief get cell_offset, offset/index of particle in cell particle data array.
 */
static __attribute__((always_inline)) INLINE size_t
  part_get_cell_offset_part_struct(const struct part *restrict p) {
#ifdef USE_PART_STRUCT_ACCESSORS
  return p->_cell_offset;
#else
  return SIZE_MAX;
#endif
}


/**
 * @brief get a pointer to cell_offset, offset/index of particle in cell particle data array.
 * Use this only if you need to modify the value, i.e. if you need write access
 * to cell_offset. If you need read-only access to cell_offset, use part_get_const_cell_offset_p() instead.
 */
static __attribute__((always_inline)) INLINE size_t*
  part_get_cell_offset_p_part_struct(struct part *restrict p) {
#ifdef USE_PART_STRUCT_ACCESSORS
  return &p->_cell_offset;
#else
  return NULL;
#endif
}


/**
 * @brief get read-only access to pointer to cell_offset,
 * offset/index of particle in cell particle data array.
 * If you need write access to cell_offset, use part_get_cell_offset_p() instead.
 */
static __attribute__((always_inline)) INLINE const size_t*
  part_get_const_cell_offset_p_part_struct(const struct part *restrict p) {
#ifdef USE_PART_STRUCT_ACCESSORS
  return &p->_cell_offset;
#else
  return NULL;
#endif
}


/**
 * @brief set the value of cell_offset, offset/index of particle in cell particle data array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_cell_offset_part_struct(struct part *restrict p, const size_t cell_offset) {
#ifdef USE_PART_STRUCT_ACCESSORS
  p->_cell_offset = cell_offset;
#endif
}





/**
 * @brief get cell_part_arrays, pointer to particle data array struct of the cell this particle is located in.
 */
#ifdef USE_PART_STRUCT_ACCESSORS
static __attribute__((always_inline)) INLINE struct part_arrays*
  part_get_cell_part_arrays_part_struct(const struct part *restrict p) {
  return p->_cell_part_arrays;
}
#endif

/**
 * @brief get a pointer to cell_part_arrays, pointer to particle data array struct of the cell this particle is located in.
 * Use this only if you need to modify the value, i.e. if you need write access
 * to cell_part_arrays. If you need read-only access to cell_part_arrays, use part_get_const_cell_part_arrays_p() instead.
 */
#ifdef USE_PART_STRUCT_ACCESSORS
static __attribute__((always_inline)) INLINE struct part_arrays**
  part_get_cell_part_arrays_p_part_struct(struct part *restrict p) {
  return &p->_cell_part_arrays;
}
#endif/**
 * @brief set the value of cell_part_arrays, pointer to particle data array struct of the cell this particle is located in.
 */
#ifdef USE_PART_STRUCT_ACCESSORS
static __attribute__((always_inline)) INLINE void
  part_set_cell_part_arrays_part_struct(struct part *restrict p,  struct part_arrays* cell_part_arrays) {
  p->_cell_part_arrays = cell_part_arrays;
}
#endif




/**
 * @brief get my_int_arr, my integer,
 * for read and write access. For read-only access, use
 * part_get_const_my_int_arr() instead.
 */
static __attribute__((always_inline)) INLINE int*
  part_get_my_int_arr_part_struct(struct part *restrict p) {
  return p->_my_int_arr;
}

/**
 * @brief get my_int_arr, my integer, for read-only access.
 */
static __attribute__((always_inline)) INLINE const int*
  part_get_const_my_int_arr_part_struct(const struct part *restrict p) {
  return p->_my_int_arr;
}

/**
 * @brief get my_int_arr, my integer, by index.
 */
static __attribute__((always_inline)) INLINE int
  part_get_my_int_arr_ind_part_struct(const struct part *restrict p, const int i) {
  return p->_my_int_arr[i];
}

/**
 * @brief set all values of my_int_arr, my integer,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_int_arr_part_struct(struct part *restrict p, const int my_int_arr[4]) {
  p->_my_int_arr[0] = my_int_arr[0];
  p->_my_int_arr[1] = my_int_arr[1];
  p->_my_int_arr[2] = my_int_arr[2];
  p->_my_int_arr[3] = my_int_arr[3];
}

/**
 * @brief set the value of my_int_arr, my integer, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_int_arr_ind_part_struct(struct part *restrict p, const int i, const int my_int_arr) {
  p->_my_int_arr[i] = my_int_arr;
}




/**
 * @brief get my_long_arr, my long,
 * for read and write access. For read-only access, use
 * part_get_const_my_long_arr() instead.
 */
static __attribute__((always_inline)) INLINE long*
  part_get_my_long_arr_part_struct(struct part *restrict p) {
  return p->_my_long_arr;
}

/**
 * @brief get my_long_arr, my long, for read-only access.
 */
static __attribute__((always_inline)) INLINE const long*
  part_get_const_my_long_arr_part_struct(const struct part *restrict p) {
  return p->_my_long_arr;
}

/**
 * @brief get my_long_arr, my long, by index.
 */
static __attribute__((always_inline)) INLINE long
  part_get_my_long_arr_ind_part_struct(const struct part *restrict p, const int i) {
  return p->_my_long_arr[i];
}

/**
 * @brief set all values of my_long_arr, my long,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_long_arr_part_struct(struct part *restrict p, const long my_long_arr[4]) {
  p->_my_long_arr[0] = my_long_arr[0];
  p->_my_long_arr[1] = my_long_arr[1];
  p->_my_long_arr[2] = my_long_arr[2];
  p->_my_long_arr[3] = my_long_arr[3];
}

/**
 * @brief set the value of my_long_arr, my long, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_long_arr_ind_part_struct(struct part *restrict p, const int i, const long my_long_arr) {
  p->_my_long_arr[i] = my_long_arr;
}




/**
 * @brief get my_longlong_arr, my long long,
 * for read and write access. For read-only access, use
 * part_get_const_my_longlong_arr() instead.
 */
static __attribute__((always_inline)) INLINE long long*
  part_get_my_longlong_arr_part_struct(struct part *restrict p) {
  return p->_my_longlong_arr;
}

/**
 * @brief get my_longlong_arr, my long long, for read-only access.
 */
static __attribute__((always_inline)) INLINE const long long*
  part_get_const_my_longlong_arr_part_struct(const struct part *restrict p) {
  return p->_my_longlong_arr;
}

/**
 * @brief get my_longlong_arr, my long long, by index.
 */
static __attribute__((always_inline)) INLINE long long
  part_get_my_longlong_arr_ind_part_struct(const struct part *restrict p, const int i) {
  return p->_my_longlong_arr[i];
}

/**
 * @brief set all values of my_longlong_arr, my long long,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_longlong_arr_part_struct(struct part *restrict p, const long long my_longlong_arr[4]) {
  p->_my_longlong_arr[0] = my_longlong_arr[0];
  p->_my_longlong_arr[1] = my_longlong_arr[1];
  p->_my_longlong_arr[2] = my_longlong_arr[2];
  p->_my_longlong_arr[3] = my_longlong_arr[3];
}

/**
 * @brief set the value of my_longlong_arr, my long long, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_longlong_arr_ind_part_struct(struct part *restrict p, const int i, const long long my_longlong_arr) {
  p->_my_longlong_arr[i] = my_longlong_arr;
}




/**
 * @brief get my_float_arr, my float,
 * for read and write access. For read-only access, use
 * part_get_const_my_float_arr() instead.
 */
static __attribute__((always_inline)) INLINE float*
  part_get_my_float_arr_part_struct(struct part *restrict p) {
  return p->_my_float_arr;
}

/**
 * @brief get my_float_arr, my float, for read-only access.
 */
static __attribute__((always_inline)) INLINE const float*
  part_get_const_my_float_arr_part_struct(const struct part *restrict p) {
  return p->_my_float_arr;
}

/**
 * @brief get my_float_arr, my float, by index.
 */
static __attribute__((always_inline)) INLINE float
  part_get_my_float_arr_ind_part_struct(const struct part *restrict p, const int i) {
  return p->_my_float_arr[i];
}

/**
 * @brief set all values of my_float_arr, my float,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_float_arr_part_struct(struct part *restrict p, const float my_float_arr[4]) {
  p->_my_float_arr[0] = my_float_arr[0];
  p->_my_float_arr[1] = my_float_arr[1];
  p->_my_float_arr[2] = my_float_arr[2];
  p->_my_float_arr[3] = my_float_arr[3];
}

/**
 * @brief set the value of my_float_arr, my float, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_float_arr_ind_part_struct(struct part *restrict p, const int i, const float my_float_arr) {
  p->_my_float_arr[i] = my_float_arr;
}




/**
 * @brief get my_dble_arr, my double,
 * for read and write access. For read-only access, use
 * part_get_const_my_dble_arr() instead.
 */
static __attribute__((always_inline)) INLINE double*
  part_get_my_dble_arr_part_struct(struct part *restrict p) {
  return p->_my_dble_arr;
}

/**
 * @brief get my_dble_arr, my double, for read-only access.
 */
static __attribute__((always_inline)) INLINE const double*
  part_get_const_my_dble_arr_part_struct(const struct part *restrict p) {
  return p->_my_dble_arr;
}

/**
 * @brief get my_dble_arr, my double, by index.
 */
static __attribute__((always_inline)) INLINE double
  part_get_my_dble_arr_ind_part_struct(const struct part *restrict p, const int i) {
  return p->_my_dble_arr[i];
}

/**
 * @brief set all values of my_dble_arr, my double,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_dble_arr_part_struct(struct part *restrict p, const double my_dble_arr[4]) {
  p->_my_dble_arr[0] = my_dble_arr[0];
  p->_my_dble_arr[1] = my_dble_arr[1];
  p->_my_dble_arr[2] = my_dble_arr[2];
  p->_my_dble_arr[3] = my_dble_arr[3];
}

/**
 * @brief set the value of my_dble_arr, my double, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_dble_arr_ind_part_struct(struct part *restrict p, const int i, const double my_dble_arr) {
  p->_my_dble_arr[i] = my_dble_arr;
}




/**
 * @brief get my_char_arr, my_char,
 * for read and write access. For read-only access, use
 * part_get_const_my_char_arr() instead.
 */
static __attribute__((always_inline)) INLINE char*
  part_get_my_char_arr_part_struct(struct part *restrict p) {
  return p->_my_char_arr;
}

/**
 * @brief get my_char_arr, my_char, for read-only access.
 */
static __attribute__((always_inline)) INLINE const char*
  part_get_const_my_char_arr_part_struct(const struct part *restrict p) {
  return p->_my_char_arr;
}

/**
 * @brief get my_char_arr, my_char, by index.
 */
static __attribute__((always_inline)) INLINE char
  part_get_my_char_arr_ind_part_struct(const struct part *restrict p, const int i) {
  return p->_my_char_arr[i];
}

/**
 * @brief set all values of my_char_arr, my_char,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_char_arr_part_struct(struct part *restrict p, const char my_char_arr[4]) {
  p->_my_char_arr[0] = my_char_arr[0];
  p->_my_char_arr[1] = my_char_arr[1];
  p->_my_char_arr[2] = my_char_arr[2];
  p->_my_char_arr[3] = my_char_arr[3];
}

/**
 * @brief set the value of my_char_arr, my_char, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_char_arr_ind_part_struct(struct part *restrict p, const int i, const char my_char_arr) {
  p->_my_char_arr[i] = my_char_arr;
}




/**
 * @brief get my_integertime_arr, my integertime,
 * for read and write access. For read-only access, use
 * part_get_const_my_integertime_arr() instead.
 */
static __attribute__((always_inline)) INLINE integertime_t*
  part_get_my_integertime_arr_part_struct(struct part *restrict p) {
  return p->_my_integertime_arr;
}

/**
 * @brief get my_integertime_arr, my integertime, for read-only access.
 */
static __attribute__((always_inline)) INLINE const integertime_t*
  part_get_const_my_integertime_arr_part_struct(const struct part *restrict p) {
  return p->_my_integertime_arr;
}

/**
 * @brief get my_integertime_arr, my integertime, by index.
 */
static __attribute__((always_inline)) INLINE integertime_t
  part_get_my_integertime_arr_ind_part_struct(const struct part *restrict p, const int i) {
  return p->_my_integertime_arr[i];
}

/**
 * @brief set all values of my_integertime_arr, my integertime,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_integertime_arr_part_struct(struct part *restrict p, const integertime_t my_integertime_arr[4]) {
  p->_my_integertime_arr[0] = my_integertime_arr[0];
  p->_my_integertime_arr[1] = my_integertime_arr[1];
  p->_my_integertime_arr[2] = my_integertime_arr[2];
  p->_my_integertime_arr[3] = my_integertime_arr[3];
}

/**
 * @brief set the value of my_integertime_arr, my integertime, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_integertime_arr_ind_part_struct(struct part *restrict p, const int i, const integertime_t my_integertime_arr) {
  p->_my_integertime_arr[i] = my_integertime_arr;
}




/**
 * @brief get my_timebin_arr, my timebin,
 * for read and write access. For read-only access, use
 * part_get_const_my_timebin_arr() instead.
 */
static __attribute__((always_inline)) INLINE timebin_t*
  part_get_my_timebin_arr_part_struct(struct part *restrict p) {
  return p->_my_timebin_arr;
}

/**
 * @brief get my_timebin_arr, my timebin, for read-only access.
 */
static __attribute__((always_inline)) INLINE const timebin_t*
  part_get_const_my_timebin_arr_part_struct(const struct part *restrict p) {
  return p->_my_timebin_arr;
}

/**
 * @brief get my_timebin_arr, my timebin, by index.
 */
static __attribute__((always_inline)) INLINE timebin_t
  part_get_my_timebin_arr_ind_part_struct(const struct part *restrict p, const int i) {
  return p->_my_timebin_arr[i];
}

/**
 * @brief set all values of my_timebin_arr, my timebin,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_timebin_arr_part_struct(struct part *restrict p, const timebin_t my_timebin_arr[4]) {
  p->_my_timebin_arr[0] = my_timebin_arr[0];
  p->_my_timebin_arr[1] = my_timebin_arr[1];
  p->_my_timebin_arr[2] = my_timebin_arr[2];
  p->_my_timebin_arr[3] = my_timebin_arr[3];
}

/**
 * @brief set the value of my_timebin_arr, my timebin, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_timebin_arr_ind_part_struct(struct part *restrict p, const int i, const timebin_t my_timebin_arr) {
  p->_my_timebin_arr[i] = my_timebin_arr;
}




/**
 * @brief get my_external_struct_arr, some externally defined struct,
 * for read and write access. For read-only access, use
 * part_get_const_my_external_struct_arr() instead.
 */
static __attribute__((always_inline)) INLINE struct my_struct*
  part_get_my_external_struct_arr_part_struct(struct part *restrict p) {
  return p->_my_external_struct_arr;
}

/**
 * @brief get my_external_struct_arr, some externally defined struct, for read-only access.
 */
static __attribute__((always_inline)) INLINE const struct my_struct*
  part_get_const_my_external_struct_arr_part_struct(const struct part *restrict p) {
  return p->_my_external_struct_arr;
}

/**
 * @brief get my_external_struct_arr, some externally defined struct, by index.
 */
static __attribute__((always_inline)) INLINE struct my_struct
  part_get_my_external_struct_arr_ind_part_struct(const struct part *restrict p, const int i) {
  return p->_my_external_struct_arr[i];
}

/**
 * @brief set all values of my_external_struct_arr, some externally defined struct,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_external_struct_arr_part_struct(struct part *restrict p, const struct my_struct my_external_struct_arr[4]) {
  p->_my_external_struct_arr[0] = my_external_struct_arr[0];
  p->_my_external_struct_arr[1] = my_external_struct_arr[1];
  p->_my_external_struct_arr[2] = my_external_struct_arr[2];
  p->_my_external_struct_arr[3] = my_external_struct_arr[3];
}

/**
 * @brief set the value of my_external_struct_arr, some externally defined struct, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_external_struct_arr_ind_part_struct(struct part *restrict p, const int i, const struct my_struct my_external_struct_arr) {
  p->_my_external_struct_arr[i] = my_external_struct_arr;
}






/**
 * @brief get my_int_arr2, my integer,
 * for read and write access. For read-only access, use
 * part_get_const_my_int_arr2() instead.
 */
static __attribute__((always_inline)) INLINE int*
  part_get_my_int_arr2_part_struct(struct part *restrict p) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_int_arr2;
}

/**
 * @brief get my_int_arr2, my integer, for read-only access.
 */
static __attribute__((always_inline)) INLINE const int*
  part_get_const_my_int_arr2_part_struct(const struct part *restrict p) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_int_arr2;
}

/**
 * @brief get my_int_arr2, my integer, by index.
 */
static __attribute__((always_inline)) INLINE int
  part_get_my_int_arr2_ind_part_struct(const struct part *restrict p, const int i) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_int_arr2[i];
}

/**
 * @brief set all values of my_int_arr2, my integer,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_int_arr2_part_struct(struct part *restrict p, const int my_int_arr2[4]) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  part2_s->_my_int_arr2[0] = my_int_arr2[0];
  part2_s->_my_int_arr2[1] = my_int_arr2[1];
  part2_s->_my_int_arr2[2] = my_int_arr2[2];
  part2_s->_my_int_arr2[3] = my_int_arr2[3];
}

/**
 * @brief set the value of my_int_arr2, my integer, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_int_arr2_ind_part_struct(struct part *restrict p, const int i, const int my_int_arr2) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
      #endif
  part2_s->_my_int_arr2[i] = my_int_arr2;
}




/**
 * @brief get my_long_arr2, my long,
 * for read and write access. For read-only access, use
 * part_get_const_my_long_arr2() instead.
 */
static __attribute__((always_inline)) INLINE long*
  part_get_my_long_arr2_part_struct(struct part *restrict p) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_long_arr2;
}

/**
 * @brief get my_long_arr2, my long, for read-only access.
 */
static __attribute__((always_inline)) INLINE const long*
  part_get_const_my_long_arr2_part_struct(const struct part *restrict p) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_long_arr2;
}

/**
 * @brief get my_long_arr2, my long, by index.
 */
static __attribute__((always_inline)) INLINE long
  part_get_my_long_arr2_ind_part_struct(const struct part *restrict p, const int i) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_long_arr2[i];
}

/**
 * @brief set all values of my_long_arr2, my long,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_long_arr2_part_struct(struct part *restrict p, const long my_long_arr2[4]) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  part2_s->_my_long_arr2[0] = my_long_arr2[0];
  part2_s->_my_long_arr2[1] = my_long_arr2[1];
  part2_s->_my_long_arr2[2] = my_long_arr2[2];
  part2_s->_my_long_arr2[3] = my_long_arr2[3];
}

/**
 * @brief set the value of my_long_arr2, my long, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_long_arr2_ind_part_struct(struct part *restrict p, const int i, const long my_long_arr2) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
      #endif
  part2_s->_my_long_arr2[i] = my_long_arr2;
}




/**
 * @brief get my_longlong_arr2, my long long,
 * for read and write access. For read-only access, use
 * part_get_const_my_longlong_arr2() instead.
 */
static __attribute__((always_inline)) INLINE long long*
  part_get_my_longlong_arr2_part_struct(struct part *restrict p) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_longlong_arr2;
}

/**
 * @brief get my_longlong_arr2, my long long, for read-only access.
 */
static __attribute__((always_inline)) INLINE const long long*
  part_get_const_my_longlong_arr2_part_struct(const struct part *restrict p) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_longlong_arr2;
}

/**
 * @brief get my_longlong_arr2, my long long, by index.
 */
static __attribute__((always_inline)) INLINE long long
  part_get_my_longlong_arr2_ind_part_struct(const struct part *restrict p, const int i) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_longlong_arr2[i];
}

/**
 * @brief set all values of my_longlong_arr2, my long long,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_longlong_arr2_part_struct(struct part *restrict p, const long long my_longlong_arr2[4]) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  part2_s->_my_longlong_arr2[0] = my_longlong_arr2[0];
  part2_s->_my_longlong_arr2[1] = my_longlong_arr2[1];
  part2_s->_my_longlong_arr2[2] = my_longlong_arr2[2];
  part2_s->_my_longlong_arr2[3] = my_longlong_arr2[3];
}

/**
 * @brief set the value of my_longlong_arr2, my long long, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_longlong_arr2_ind_part_struct(struct part *restrict p, const int i, const long long my_longlong_arr2) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
      #endif
  part2_s->_my_longlong_arr2[i] = my_longlong_arr2;
}




/**
 * @brief get my_float_arr2, my float,
 * for read and write access. For read-only access, use
 * part_get_const_my_float_arr2() instead.
 */
static __attribute__((always_inline)) INLINE float*
  part_get_my_float_arr2_part_struct(struct part *restrict p) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_float_arr2;
}

/**
 * @brief get my_float_arr2, my float, for read-only access.
 */
static __attribute__((always_inline)) INLINE const float*
  part_get_const_my_float_arr2_part_struct(const struct part *restrict p) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_float_arr2;
}

/**
 * @brief get my_float_arr2, my float, by index.
 */
static __attribute__((always_inline)) INLINE float
  part_get_my_float_arr2_ind_part_struct(const struct part *restrict p, const int i) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_float_arr2[i];
}

/**
 * @brief set all values of my_float_arr2, my float,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_float_arr2_part_struct(struct part *restrict p, const float my_float_arr2[4]) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  part2_s->_my_float_arr2[0] = my_float_arr2[0];
  part2_s->_my_float_arr2[1] = my_float_arr2[1];
  part2_s->_my_float_arr2[2] = my_float_arr2[2];
  part2_s->_my_float_arr2[3] = my_float_arr2[3];
}

/**
 * @brief set the value of my_float_arr2, my float, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_float_arr2_ind_part_struct(struct part *restrict p, const int i, const float my_float_arr2) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
      #endif
  part2_s->_my_float_arr2[i] = my_float_arr2;
}




/**
 * @brief get my_dble_arr2, my double,
 * for read and write access. For read-only access, use
 * part_get_const_my_dble_arr2() instead.
 */
static __attribute__((always_inline)) INLINE double*
  part_get_my_dble_arr2_part_struct(struct part *restrict p) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_dble_arr2;
}

/**
 * @brief get my_dble_arr2, my double, for read-only access.
 */
static __attribute__((always_inline)) INLINE const double*
  part_get_const_my_dble_arr2_part_struct(const struct part *restrict p) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_dble_arr2;
}

/**
 * @brief get my_dble_arr2, my double, by index.
 */
static __attribute__((always_inline)) INLINE double
  part_get_my_dble_arr2_ind_part_struct(const struct part *restrict p, const int i) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_dble_arr2[i];
}

/**
 * @brief set all values of my_dble_arr2, my double,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_dble_arr2_part_struct(struct part *restrict p, const double my_dble_arr2[4]) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  part2_s->_my_dble_arr2[0] = my_dble_arr2[0];
  part2_s->_my_dble_arr2[1] = my_dble_arr2[1];
  part2_s->_my_dble_arr2[2] = my_dble_arr2[2];
  part2_s->_my_dble_arr2[3] = my_dble_arr2[3];
}

/**
 * @brief set the value of my_dble_arr2, my double, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_dble_arr2_ind_part_struct(struct part *restrict p, const int i, const double my_dble_arr2) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
      #endif
  part2_s->_my_dble_arr2[i] = my_dble_arr2;
}




/**
 * @brief get my_char_arr2, my_char,
 * for read and write access. For read-only access, use
 * part_get_const_my_char_arr2() instead.
 */
static __attribute__((always_inline)) INLINE char*
  part_get_my_char_arr2_part_struct(struct part *restrict p) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_char_arr2;
}

/**
 * @brief get my_char_arr2, my_char, for read-only access.
 */
static __attribute__((always_inline)) INLINE const char*
  part_get_const_my_char_arr2_part_struct(const struct part *restrict p) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_char_arr2;
}

/**
 * @brief get my_char_arr2, my_char, by index.
 */
static __attribute__((always_inline)) INLINE char
  part_get_my_char_arr2_ind_part_struct(const struct part *restrict p, const int i) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_char_arr2[i];
}

/**
 * @brief set all values of my_char_arr2, my_char,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_char_arr2_part_struct(struct part *restrict p, const char my_char_arr2[4]) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  part2_s->_my_char_arr2[0] = my_char_arr2[0];
  part2_s->_my_char_arr2[1] = my_char_arr2[1];
  part2_s->_my_char_arr2[2] = my_char_arr2[2];
  part2_s->_my_char_arr2[3] = my_char_arr2[3];
}

/**
 * @brief set the value of my_char_arr2, my_char, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_char_arr2_ind_part_struct(struct part *restrict p, const int i, const char my_char_arr2) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
      #endif
  part2_s->_my_char_arr2[i] = my_char_arr2;
}




/**
 * @brief get my_integertime_arr2, my integertime,
 * for read and write access. For read-only access, use
 * part_get_const_my_integertime_arr2() instead.
 */
static __attribute__((always_inline)) INLINE integertime_t*
  part_get_my_integertime_arr2_part_struct(struct part *restrict p) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_integertime_arr2;
}

/**
 * @brief get my_integertime_arr2, my integertime, for read-only access.
 */
static __attribute__((always_inline)) INLINE const integertime_t*
  part_get_const_my_integertime_arr2_part_struct(const struct part *restrict p) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_integertime_arr2;
}

/**
 * @brief get my_integertime_arr2, my integertime, by index.
 */
static __attribute__((always_inline)) INLINE integertime_t
  part_get_my_integertime_arr2_ind_part_struct(const struct part *restrict p, const int i) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_integertime_arr2[i];
}

/**
 * @brief set all values of my_integertime_arr2, my integertime,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_integertime_arr2_part_struct(struct part *restrict p, const integertime_t my_integertime_arr2[4]) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  part2_s->_my_integertime_arr2[0] = my_integertime_arr2[0];
  part2_s->_my_integertime_arr2[1] = my_integertime_arr2[1];
  part2_s->_my_integertime_arr2[2] = my_integertime_arr2[2];
  part2_s->_my_integertime_arr2[3] = my_integertime_arr2[3];
}

/**
 * @brief set the value of my_integertime_arr2, my integertime, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_integertime_arr2_ind_part_struct(struct part *restrict p, const int i, const integertime_t my_integertime_arr2) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
      #endif
  part2_s->_my_integertime_arr2[i] = my_integertime_arr2;
}




/**
 * @brief get my_timebin_arr2, my timebin,
 * for read and write access. For read-only access, use
 * part_get_const_my_timebin_arr2() instead.
 */
static __attribute__((always_inline)) INLINE timebin_t*
  part_get_my_timebin_arr2_part_struct(struct part *restrict p) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_timebin_arr2;
}

/**
 * @brief get my_timebin_arr2, my timebin, for read-only access.
 */
static __attribute__((always_inline)) INLINE const timebin_t*
  part_get_const_my_timebin_arr2_part_struct(const struct part *restrict p) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_timebin_arr2;
}

/**
 * @brief get my_timebin_arr2, my timebin, by index.
 */
static __attribute__((always_inline)) INLINE timebin_t
  part_get_my_timebin_arr2_ind_part_struct(const struct part *restrict p, const int i) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_timebin_arr2[i];
}

/**
 * @brief set all values of my_timebin_arr2, my timebin,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_timebin_arr2_part_struct(struct part *restrict p, const timebin_t my_timebin_arr2[4]) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  part2_s->_my_timebin_arr2[0] = my_timebin_arr2[0];
  part2_s->_my_timebin_arr2[1] = my_timebin_arr2[1];
  part2_s->_my_timebin_arr2[2] = my_timebin_arr2[2];
  part2_s->_my_timebin_arr2[3] = my_timebin_arr2[3];
}

/**
 * @brief set the value of my_timebin_arr2, my timebin, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_timebin_arr2_ind_part_struct(struct part *restrict p, const int i, const timebin_t my_timebin_arr2) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
      #endif
  part2_s->_my_timebin_arr2[i] = my_timebin_arr2;
}




/**
 * @brief get my_external_struct_arr2, some externally defined struct,
 * for read and write access. For read-only access, use
 * part_get_const_my_external_struct_arr2() instead.
 */
static __attribute__((always_inline)) INLINE struct my_struct*
  part_get_my_external_struct_arr2_part_struct(struct part *restrict p) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_external_struct_arr2;
}

/**
 * @brief get my_external_struct_arr2, some externally defined struct, for read-only access.
 */
static __attribute__((always_inline)) INLINE const struct my_struct*
  part_get_const_my_external_struct_arr2_part_struct(const struct part *restrict p) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_external_struct_arr2;
}

/**
 * @brief get my_external_struct_arr2, some externally defined struct, by index.
 */
static __attribute__((always_inline)) INLINE struct my_struct
  part_get_my_external_struct_arr2_ind_part_struct(const struct part *restrict p, const int i) {
  const struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  return part2_s->_my_external_struct_arr2[i];
}

/**
 * @brief set all values of my_external_struct_arr2, some externally defined struct,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_external_struct_arr2_part_struct(struct part *restrict p, const struct my_struct my_external_struct_arr2[4]) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
#endif
  part2_s->_my_external_struct_arr2[0] = my_external_struct_arr2[0];
  part2_s->_my_external_struct_arr2[1] = my_external_struct_arr2[1];
  part2_s->_my_external_struct_arr2[2] = my_external_struct_arr2[2];
  part2_s->_my_external_struct_arr2[3] = my_external_struct_arr2[3];
}

/**
 * @brief set the value of my_external_struct_arr2, some externally defined struct, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_external_struct_arr2_ind_part_struct(struct part *restrict p, const int i, const struct my_struct my_external_struct_arr2) {
  struct part2* restrict part2_s = p->_cell_part_arrays->_part2 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part2_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part2_s->_accessor_id, p->_accessor_id);
      #endif
  part2_s->_my_external_struct_arr2[i] = my_external_struct_arr2;
}






/**
 * @brief get my_int_arr3, my integer,
 * for read and write access. For read-only access, use
 * part_get_const_my_int_arr3() instead.
 */
static __attribute__((always_inline)) INLINE int*
  part_get_my_int_arr3_part_struct(struct part *restrict p) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_int_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_int_arr3, my integer, for read-only access.
 */
static __attribute__((always_inline)) INLINE const int*
  part_get_const_my_int_arr3_part_struct(const struct part *restrict p) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_int_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_int_arr3, my integer, by index.
 */
static __attribute__((always_inline)) INLINE int
  part_get_my_int_arr3_ind_part_struct(const struct part *restrict p, const int i) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_int_arr3[i];
#else
  return INT_MAX;
#endif
}

/**
 * @brief set all values of my_int_arr3, my integer,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_int_arr3_part_struct(struct part *restrict p, const int my_int_arr3[4]) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  part3_s->_my_int_arr3[0] = my_int_arr3[0];
  part3_s->_my_int_arr3[1] = my_int_arr3[1];
  part3_s->_my_int_arr3[2] = my_int_arr3[2];
  part3_s->_my_int_arr3[3] = my_int_arr3[3];
#endif
}

/**
 * @brief set the value of my_int_arr3, my integer, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_int_arr3_ind_part_struct(struct part *restrict p, const int i, const int my_int_arr3) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
      #endif
  part3_s->_my_int_arr3[i] = my_int_arr3;
#endif
}




/**
 * @brief get my_long_arr3, my long,
 * for read and write access. For read-only access, use
 * part_get_const_my_long_arr3() instead.
 */
static __attribute__((always_inline)) INLINE long*
  part_get_my_long_arr3_part_struct(struct part *restrict p) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_long_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_long_arr3, my long, for read-only access.
 */
static __attribute__((always_inline)) INLINE const long*
  part_get_const_my_long_arr3_part_struct(const struct part *restrict p) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_long_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_long_arr3, my long, by index.
 */
static __attribute__((always_inline)) INLINE long
  part_get_my_long_arr3_ind_part_struct(const struct part *restrict p, const int i) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_long_arr3[i];
#else
  return LONG_MAX;
#endif
}

/**
 * @brief set all values of my_long_arr3, my long,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_long_arr3_part_struct(struct part *restrict p, const long my_long_arr3[4]) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  part3_s->_my_long_arr3[0] = my_long_arr3[0];
  part3_s->_my_long_arr3[1] = my_long_arr3[1];
  part3_s->_my_long_arr3[2] = my_long_arr3[2];
  part3_s->_my_long_arr3[3] = my_long_arr3[3];
#endif
}

/**
 * @brief set the value of my_long_arr3, my long, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_long_arr3_ind_part_struct(struct part *restrict p, const int i, const long my_long_arr3) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
      #endif
  part3_s->_my_long_arr3[i] = my_long_arr3;
#endif
}




/**
 * @brief get my_longlong_arr3, my long long,
 * for read and write access. For read-only access, use
 * part_get_const_my_longlong_arr3() instead.
 */
static __attribute__((always_inline)) INLINE long long*
  part_get_my_longlong_arr3_part_struct(struct part *restrict p) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_longlong_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_longlong_arr3, my long long, for read-only access.
 */
static __attribute__((always_inline)) INLINE const long long*
  part_get_const_my_longlong_arr3_part_struct(const struct part *restrict p) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_longlong_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_longlong_arr3, my long long, by index.
 */
static __attribute__((always_inline)) INLINE long long
  part_get_my_longlong_arr3_ind_part_struct(const struct part *restrict p, const int i) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_longlong_arr3[i];
#else
  return LLONG_MAX;
#endif
}

/**
 * @brief set all values of my_longlong_arr3, my long long,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_longlong_arr3_part_struct(struct part *restrict p, const long long my_longlong_arr3[4]) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  part3_s->_my_longlong_arr3[0] = my_longlong_arr3[0];
  part3_s->_my_longlong_arr3[1] = my_longlong_arr3[1];
  part3_s->_my_longlong_arr3[2] = my_longlong_arr3[2];
  part3_s->_my_longlong_arr3[3] = my_longlong_arr3[3];
#endif
}

/**
 * @brief set the value of my_longlong_arr3, my long long, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_longlong_arr3_ind_part_struct(struct part *restrict p, const int i, const long long my_longlong_arr3) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
      #endif
  part3_s->_my_longlong_arr3[i] = my_longlong_arr3;
#endif
}




/**
 * @brief get my_float_arr3, my float,
 * for read and write access. For read-only access, use
 * part_get_const_my_float_arr3() instead.
 */
static __attribute__((always_inline)) INLINE float*
  part_get_my_float_arr3_part_struct(struct part *restrict p) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_float_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_float_arr3, my float, for read-only access.
 */
static __attribute__((always_inline)) INLINE const float*
  part_get_const_my_float_arr3_part_struct(const struct part *restrict p) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_float_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_float_arr3, my float, by index.
 */
static __attribute__((always_inline)) INLINE float
  part_get_my_float_arr3_ind_part_struct(const struct part *restrict p, const int i) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_float_arr3[i];
#else
  return FLT_MAX;
#endif
}

/**
 * @brief set all values of my_float_arr3, my float,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_float_arr3_part_struct(struct part *restrict p, const float my_float_arr3[4]) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  part3_s->_my_float_arr3[0] = my_float_arr3[0];
  part3_s->_my_float_arr3[1] = my_float_arr3[1];
  part3_s->_my_float_arr3[2] = my_float_arr3[2];
  part3_s->_my_float_arr3[3] = my_float_arr3[3];
#endif
}

/**
 * @brief set the value of my_float_arr3, my float, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_float_arr3_ind_part_struct(struct part *restrict p, const int i, const float my_float_arr3) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
      #endif
  part3_s->_my_float_arr3[i] = my_float_arr3;
#endif
}




/**
 * @brief get my_dble_arr3, my double,
 * for read and write access. For read-only access, use
 * part_get_const_my_dble_arr3() instead.
 */
static __attribute__((always_inline)) INLINE double*
  part_get_my_dble_arr3_part_struct(struct part *restrict p) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_dble_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_dble_arr3, my double, for read-only access.
 */
static __attribute__((always_inline)) INLINE const double*
  part_get_const_my_dble_arr3_part_struct(const struct part *restrict p) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_dble_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_dble_arr3, my double, by index.
 */
static __attribute__((always_inline)) INLINE double
  part_get_my_dble_arr3_ind_part_struct(const struct part *restrict p, const int i) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_dble_arr3[i];
#else
  return DBL_MAX;
#endif
}

/**
 * @brief set all values of my_dble_arr3, my double,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_dble_arr3_part_struct(struct part *restrict p, const double my_dble_arr3[4]) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  part3_s->_my_dble_arr3[0] = my_dble_arr3[0];
  part3_s->_my_dble_arr3[1] = my_dble_arr3[1];
  part3_s->_my_dble_arr3[2] = my_dble_arr3[2];
  part3_s->_my_dble_arr3[3] = my_dble_arr3[3];
#endif
}

/**
 * @brief set the value of my_dble_arr3, my double, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_dble_arr3_ind_part_struct(struct part *restrict p, const int i, const double my_dble_arr3) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
      #endif
  part3_s->_my_dble_arr3[i] = my_dble_arr3;
#endif
}




/**
 * @brief get my_char_arr3, my_char,
 * for read and write access. For read-only access, use
 * part_get_const_my_char_arr3() instead.
 */
static __attribute__((always_inline)) INLINE char*
  part_get_my_char_arr3_part_struct(struct part *restrict p) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_char_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_char_arr3, my_char, for read-only access.
 */
static __attribute__((always_inline)) INLINE const char*
  part_get_const_my_char_arr3_part_struct(const struct part *restrict p) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_char_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_char_arr3, my_char, by index.
 */
static __attribute__((always_inline)) INLINE char
  part_get_my_char_arr3_ind_part_struct(const struct part *restrict p, const int i) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_char_arr3[i];
#else
  return CHAR_MAX;
#endif
}

/**
 * @brief set all values of my_char_arr3, my_char,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_char_arr3_part_struct(struct part *restrict p, const char my_char_arr3[4]) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  part3_s->_my_char_arr3[0] = my_char_arr3[0];
  part3_s->_my_char_arr3[1] = my_char_arr3[1];
  part3_s->_my_char_arr3[2] = my_char_arr3[2];
  part3_s->_my_char_arr3[3] = my_char_arr3[3];
#endif
}

/**
 * @brief set the value of my_char_arr3, my_char, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_char_arr3_ind_part_struct(struct part *restrict p, const int i, const char my_char_arr3) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
      #endif
  part3_s->_my_char_arr3[i] = my_char_arr3;
#endif
}




/**
 * @brief get my_integertime_arr3, my integertime,
 * for read and write access. For read-only access, use
 * part_get_const_my_integertime_arr3() instead.
 */
static __attribute__((always_inline)) INLINE integertime_t*
  part_get_my_integertime_arr3_part_struct(struct part *restrict p) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_integertime_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_integertime_arr3, my integertime, for read-only access.
 */
static __attribute__((always_inline)) INLINE const integertime_t*
  part_get_const_my_integertime_arr3_part_struct(const struct part *restrict p) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_integertime_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_integertime_arr3, my integertime, by index.
 */
static __attribute__((always_inline)) INLINE integertime_t
  part_get_my_integertime_arr3_ind_part_struct(const struct part *restrict p, const int i) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_integertime_arr3[i];
#else
  return LLONG_MAX;
#endif
}

/**
 * @brief set all values of my_integertime_arr3, my integertime,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_integertime_arr3_part_struct(struct part *restrict p, const integertime_t my_integertime_arr3[4]) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  part3_s->_my_integertime_arr3[0] = my_integertime_arr3[0];
  part3_s->_my_integertime_arr3[1] = my_integertime_arr3[1];
  part3_s->_my_integertime_arr3[2] = my_integertime_arr3[2];
  part3_s->_my_integertime_arr3[3] = my_integertime_arr3[3];
#endif
}

/**
 * @brief set the value of my_integertime_arr3, my integertime, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_integertime_arr3_ind_part_struct(struct part *restrict p, const int i, const integertime_t my_integertime_arr3) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
      #endif
  part3_s->_my_integertime_arr3[i] = my_integertime_arr3;
#endif
}




/**
 * @brief get my_timebin_arr3, my timebin,
 * for read and write access. For read-only access, use
 * part_get_const_my_timebin_arr3() instead.
 */
static __attribute__((always_inline)) INLINE timebin_t*
  part_get_my_timebin_arr3_part_struct(struct part *restrict p) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
    #ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_timebin_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_timebin_arr3, my timebin, for read-only access.
 */
static __attribute__((always_inline)) INLINE const timebin_t*
  part_get_const_my_timebin_arr3_part_struct(const struct part *restrict p) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_timebin_arr3;
#else
  return NULL;
#endif
}

/**
 * @brief get my_timebin_arr3, my timebin, by index.
 */
static __attribute__((always_inline)) INLINE timebin_t
  part_get_my_timebin_arr3_ind_part_struct(const struct part *restrict p, const int i) {
#ifdef DEBUG
  const struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  return part3_s->_my_timebin_arr3[i];
#else
  return CHAR_MAX;
#endif
}

/**
 * @brief set all values of my_timebin_arr3, my timebin,
 * from an array.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_timebin_arr3_part_struct(struct part *restrict p, const timebin_t my_timebin_arr3[4]) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
#endif
  part3_s->_my_timebin_arr3[0] = my_timebin_arr3[0];
  part3_s->_my_timebin_arr3[1] = my_timebin_arr3[1];
  part3_s->_my_timebin_arr3[2] = my_timebin_arr3[2];
  part3_s->_my_timebin_arr3[3] = my_timebin_arr3[3];
#endif
}

/**
 * @brief set the value of my_timebin_arr3, my timebin, by index.
 */
static __attribute__((always_inline)) INLINE void
  part_set_my_timebin_arr3_ind_part_struct(struct part *restrict p, const int i, const timebin_t my_timebin_arr3) {
#ifdef DEBUG
  struct part3* restrict part3_s = p->_cell_part_arrays->_part3 + p->_cell_offset;
#ifdef SWIFT_DEBUG_CHECKS
  /* Forbid ID = 0 to prevent false positives by forgotten initialisation */
  swift_assert(p->_accessor_id != 0);
  /* Make sure we're accessing the correct data */
  if(part3_s->_accessor_id != p->_accessor_id)
    error("Accessor IDs not equal: %lld %lld", part3_s->_accessor_id, p->_accessor_id);
      #endif
  part3_s->_my_timebin_arr3[i] = my_timebin_arr3;
#endif
}





#endif /* SWIFT_HYDRO_PART_TEST_H */
