
#ifndef SWIFT_HYDRO_PART_HEADER_TEST_H
#define SWIFT_HYDRO_PART_HEADER_TEST_H
/**
  * WARNING: THIS FILE WAS GENERATED. MODIFICATIONS WILL NOT STICK.
  * File template is /home/mivkov/Durham/swiftgpupacksim/py/templates/test_hydro_part.h.jinja.template
  */
/*******************************************************************************
 * Copyright (c) anonymous
 ******************************************************************************/

  
/**
 * @file /hydro_part.h
 * @brief Test file to test header outputs.
 */




#ifndef USE_PART_STRUCT_ACCESSORS
#error "USE_PART_STRUCT_ACCESSORS macro not defined. This won't compile."
#endif

#include <float.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>

#include "hydro_part_arrays_struct.h"


  
#include "align.h"
#include "error.h"
#include "hydro_part_placeholder_structs.h"
#include "hydro_part_arrays_struct.h"
#include "rt_struct.h"
#include "timestep_limiter_struct.h"
#include <float.h>
#include <limits.h>
#include <stddef.h>
#include "a.h"
#include "b.h"
#include <stdio.h>



/* Some definitions and declarations to make the test programs compile */
#ifndef MY_ARRAY_SIZE
#define MY_ARRAY_SIZE 4
#endif

#define NDIM1 2
#define NDIM2 3
#define NDIM3 4

#define INLINE inline
#define DEBUG
typedef long long integertime_t;
typedef int8_t timebin_t;

enum color {
  red = 0,
  green,
  blue,
  purple,
  white,
  black
  };

struct my_struct{};
struct gpart{
  double x[3];
  float m;
};





struct part {

  float _x;

};


/**
 * @brief get x.
 */
static __attribute__((always_inline)) INLINE float
  part_get_x_part_struct(const struct part *restrict p) {
  return p->_x;
}


/**
 * @brief get a pointer to x.
 * Use this only if you need to modify the value, i.e. if you need write access
 * to x. If you need read-only access to x, use part_get_const_x_p() instead.
 */
static __attribute__((always_inline)) INLINE float*
  part_get_x_p_part_struct(struct part *restrict p) {
  return &p->_x;
}


/**
 * @brief get read-only access to pointer to x.
 * If you need write access to x, use part_get_x_p() instead.
 */
static __attribute__((always_inline)) INLINE const float*
  part_get_const_x_p_part_struct(const struct part *restrict p) {
  return &p->_x;
}


/**
 * @brief set the value of x.
 */
static __attribute__((always_inline)) INLINE void
  part_set_x_part_struct(struct part *restrict p, const float x) {
  p->_x = x;
}




#endif /* SWIFT_HYDRO_PART_TEST_H */
