/**
  * WARNING: THIS FILE WAS GENERATED. MODIFICATIONS WILL NOT STICK.
  * File template is /home/mivkov/Durham/swiftgpupacksim/py/templates/hydro_part_arrays_struct.h.jinja.template
  */
#pragma once



/* Forward declare all part structs */

struct part;
struct part_id;
struct part_gpart;
struct part_x;
struct part_v;
struct part_a_hydro;
struct part_mass;
struct part_h;
struct part_u;
struct part_u_dt;
struct part_rho;
struct part_div_v;
struct part_div_v_dt;
struct part_div_v_previous_step;
struct part_alpha_av;
struct part_v_sig;
struct part_laplace_u;
struct part_alpha_diff;
struct part_density_force1;
struct part_density_force2;
struct part_density_force3;
struct part_density_force4;
struct part_additional_structs;
struct part_rt_time_data;
struct part_depth_h;
struct part_time_bin;
struct part_limiter_data;
struct part_ti_drift;
struct part_ti_kick;
struct part_debugging;

/**
 * Struct holding handles to all particle data arrays
 */
struct hydro_part_arrays {
 
  struct part *_part;
 
  struct part_id *_part_id;
 
  struct part_gpart *_part_gpart;
 
  struct part_x *_part_x;
 
  struct part_v *_part_v;
 
  struct part_a_hydro *_part_a_hydro;
 
  struct part_mass *_part_mass;
 
  struct part_h *_part_h;
 
  struct part_u *_part_u;
 
  struct part_u_dt *_part_u_dt;
 
  struct part_rho *_part_rho;
 
  struct part_div_v *_part_div_v;
 
  struct part_div_v_dt *_part_div_v_dt;
 
  struct part_div_v_previous_step *_part_div_v_previous_step;
 
  struct part_alpha_av *_part_alpha_av;
 
  struct part_v_sig *_part_v_sig;
 
  struct part_laplace_u *_part_laplace_u;
 
  struct part_alpha_diff *_part_alpha_diff;
 
  struct part_density_force1 *_part_density_force1;
 
  struct part_density_force2 *_part_density_force2;
 
  struct part_density_force3 *_part_density_force3;
 
  struct part_density_force4 *_part_density_force4;
 
  struct part_additional_structs *_part_additional_structs;
 
  struct part_rt_time_data *_part_rt_time_data;
 
  struct part_depth_h *_part_depth_h;
 
  struct part_time_bin *_part_time_bin;
 
  struct part_limiter_data *_part_limiter_data;
 
  struct part_ti_drift *_part_ti_drift;
 
  struct part_ti_kick *_part_ti_kick;
 
  struct part_debugging *_part_debugging;

#ifdef SWIFT_DEBUG_CHECKS
  int nr_parts;
#endif
};

