/**
  * WARNING: THIS FILE WAS GENERATED. MODIFICATIONS WILL NOT STICK.
  * File template is /home/mivkov/Durham/swiftgpupacksim/py/templates/hydro_part_arrays_flush.h.jinja.template
  */
#pragma once

#include "flush_caches_x86.h"
#include "hydro_part.h"




#ifdef SWIFT_CACHE_FLUSH_X86
/**
 * @brief flushes all particle data from caches.
 * 
 * @param part_data: Array containing all particle data
 * @param nr_parts: Number of particles in part_data array.
 */
__attribute__((always_inline)) INLINE void hydro_part_arrays_flush_from_cache(
  struct hydro_part_arrays* part_data, size_t nr_parts) {


	size_t len_part = nr_parts / sizeof(struct part) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part, len_part);


	size_t len_part_id = nr_parts / sizeof(struct part_id) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_id, len_part_id);


	size_t len_part_gpart = nr_parts / sizeof(struct part_gpart) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_gpart, len_part_gpart);


	size_t len_part_x = nr_parts / sizeof(struct part_x) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_x, len_part_x);


	size_t len_part_v = nr_parts / sizeof(struct part_v) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_v, len_part_v);


	size_t len_part_a_hydro = nr_parts / sizeof(struct part_a_hydro) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_a_hydro, len_part_a_hydro);


	size_t len_part_mass = nr_parts / sizeof(struct part_mass) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_mass, len_part_mass);


	size_t len_part_h = nr_parts / sizeof(struct part_h) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_h, len_part_h);


	size_t len_part_u = nr_parts / sizeof(struct part_u) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_u, len_part_u);


	size_t len_part_u_dt = nr_parts / sizeof(struct part_u_dt) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_u_dt, len_part_u_dt);


	size_t len_part_rho = nr_parts / sizeof(struct part_rho) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_rho, len_part_rho);


	size_t len_part_div_v = nr_parts / sizeof(struct part_div_v) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_div_v, len_part_div_v);


	size_t len_part_div_v_dt = nr_parts / sizeof(struct part_div_v_dt) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_div_v_dt, len_part_div_v_dt);


	size_t len_part_div_v_previous_step = nr_parts / sizeof(struct part_div_v_previous_step) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_div_v_previous_step, len_part_div_v_previous_step);


	size_t len_part_alpha_av = nr_parts / sizeof(struct part_alpha_av) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_alpha_av, len_part_alpha_av);


	size_t len_part_v_sig = nr_parts / sizeof(struct part_v_sig) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_v_sig, len_part_v_sig);


	size_t len_part_laplace_u = nr_parts / sizeof(struct part_laplace_u) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_laplace_u, len_part_laplace_u);


	size_t len_part_alpha_diff = nr_parts / sizeof(struct part_alpha_diff) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_alpha_diff, len_part_alpha_diff);


	size_t len_part_density1 = nr_parts / sizeof(struct part_density1) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_density1, len_part_density1);


	size_t len_part_force1 = nr_parts / sizeof(struct part_force1) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_force1, len_part_force1);


	size_t len_part_density2 = nr_parts / sizeof(struct part_density2) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_density2, len_part_density2);


	size_t len_part_force2 = nr_parts / sizeof(struct part_force2) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_force2, len_part_force2);


	size_t len_part_density3 = nr_parts / sizeof(struct part_density3) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_density3, len_part_density3);


	size_t len_part_force3 = nr_parts / sizeof(struct part_force3) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_force3, len_part_force3);


	size_t len_part_density4 = nr_parts / sizeof(struct part_density4) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_density4, len_part_density4);


	size_t len_part_force4 = nr_parts / sizeof(struct part_force4) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_force4, len_part_force4);


	size_t len_part_force5 = nr_parts / sizeof(struct part_force5) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_force5, len_part_force5);


	size_t len_part_force6 = nr_parts / sizeof(struct part_force6) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_force6, len_part_force6);


	size_t len_part_additional_structs = nr_parts / sizeof(struct part_additional_structs) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_additional_structs, len_part_additional_structs);


	size_t len_part_rt_time_data = nr_parts / sizeof(struct part_rt_time_data) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_rt_time_data, len_part_rt_time_data);


	size_t len_part_depth_h = nr_parts / sizeof(struct part_depth_h) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_depth_h, len_part_depth_h);


	size_t len_part_time_bin = nr_parts / sizeof(struct part_time_bin) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_time_bin, len_part_time_bin);


	size_t len_part_limiter_data = nr_parts / sizeof(struct part_limiter_data) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_limiter_data, len_part_limiter_data);


	size_t len_part_ti_drift = nr_parts / sizeof(struct part_ti_drift) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_ti_drift, len_part_ti_drift);


	size_t len_part_ti_kick = nr_parts / sizeof(struct part_ti_kick) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_ti_kick, len_part_ti_kick);


	size_t len_part_debugging = nr_parts / sizeof(struct part_debugging) * sizeof(char);
	flush_cache_x86_nofence((char*)part_data->_part_debugging, len_part_debugging);



  flush_cache_x86_fence();
}
#endif


