/**
  * WARNING: THIS FILE WAS GENERATED. MODIFICATIONS WILL NOT STICK.
  * File template is /cosma/home/do009/dc-ivko1/swiftgpupacksim/py/templates/parts.h.jinja.template
  */
#pragma once



#include "hydro_part.h"
#include "hydro_part_arrays_struct.h"

#include "swift_placeholders/error.h"
#include "swift_placeholders/inline.h"
#include "swift_placeholders/memuse.h"

#include <string.h> /* for memset() */



/**
 * Allocate particle data array(s).
 */
static __attribute__((always_inline)) INLINE void init_part_arrays(struct hydro_part_arrays* parr, int nr_parts) {

  if (swift_memalign("parts_part", (void**)&parr->_part, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part, 0, nr_parts * sizeof(struct part));

  if (swift_memalign("parts_part_id", (void**)&parr->_part_id, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_id)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_id, 0, nr_parts * sizeof(struct part_id));

  if (swift_memalign("parts_part_gpart", (void**)&parr->_part_gpart, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_gpart)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_gpart, 0, nr_parts * sizeof(struct part_gpart));

  if (swift_memalign("parts_part_x", (void**)&parr->_part_x, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_x)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_x, 0, nr_parts * sizeof(struct part_x));

  if (swift_memalign("parts_part_v", (void**)&parr->_part_v, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_v)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_v, 0, nr_parts * sizeof(struct part_v));

  if (swift_memalign("parts_part_a_hydro", (void**)&parr->_part_a_hydro, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_a_hydro)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_a_hydro, 0, nr_parts * sizeof(struct part_a_hydro));

  if (swift_memalign("parts_part_mass", (void**)&parr->_part_mass, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_mass)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_mass, 0, nr_parts * sizeof(struct part_mass));

  if (swift_memalign("parts_part_h", (void**)&parr->_part_h, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_h)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_h, 0, nr_parts * sizeof(struct part_h));

  if (swift_memalign("parts_part_u", (void**)&parr->_part_u, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_u)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_u, 0, nr_parts * sizeof(struct part_u));

  if (swift_memalign("parts_part_u_dt", (void**)&parr->_part_u_dt, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_u_dt)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_u_dt, 0, nr_parts * sizeof(struct part_u_dt));

  if (swift_memalign("parts_part_rho", (void**)&parr->_part_rho, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_rho)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_rho, 0, nr_parts * sizeof(struct part_rho));

  if (swift_memalign("parts_part_div_v", (void**)&parr->_part_div_v, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_div_v)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_div_v, 0, nr_parts * sizeof(struct part_div_v));

  if (swift_memalign("parts_part_div_v_dt", (void**)&parr->_part_div_v_dt, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_div_v_dt)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_div_v_dt, 0, nr_parts * sizeof(struct part_div_v_dt));

  if (swift_memalign("parts_part_div_v_previous_step", (void**)&parr->_part_div_v_previous_step, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_div_v_previous_step)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_div_v_previous_step, 0, nr_parts * sizeof(struct part_div_v_previous_step));

  if (swift_memalign("parts_part_alpha_av", (void**)&parr->_part_alpha_av, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_alpha_av)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_alpha_av, 0, nr_parts * sizeof(struct part_alpha_av));

  if (swift_memalign("parts_part_v_sig", (void**)&parr->_part_v_sig, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_v_sig)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_v_sig, 0, nr_parts * sizeof(struct part_v_sig));

  if (swift_memalign("parts_part_laplace_u", (void**)&parr->_part_laplace_u, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_laplace_u)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_laplace_u, 0, nr_parts * sizeof(struct part_laplace_u));

  if (swift_memalign("parts_part_alpha_diff", (void**)&parr->_part_alpha_diff, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_alpha_diff)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_alpha_diff, 0, nr_parts * sizeof(struct part_alpha_diff));

  if (swift_memalign("parts_part_density_force1", (void**)&parr->_part_density_force1, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_density_force1)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_density_force1, 0, nr_parts * sizeof(struct part_density_force1));

  if (swift_memalign("parts_part_density_force2", (void**)&parr->_part_density_force2, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_density_force2)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_density_force2, 0, nr_parts * sizeof(struct part_density_force2));

  if (swift_memalign("parts_part_density_force3", (void**)&parr->_part_density_force3, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_density_force3)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_density_force3, 0, nr_parts * sizeof(struct part_density_force3));

  if (swift_memalign("parts_part_density_force4", (void**)&parr->_part_density_force4, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_density_force4)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_density_force4, 0, nr_parts * sizeof(struct part_density_force4));

  if (swift_memalign("parts_part_additional_structs", (void**)&parr->_part_additional_structs, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_additional_structs)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_additional_structs, 0, nr_parts * sizeof(struct part_additional_structs));

  if (swift_memalign("parts_part_rt_time_data", (void**)&parr->_part_rt_time_data, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_rt_time_data)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_rt_time_data, 0, nr_parts * sizeof(struct part_rt_time_data));

  if (swift_memalign("parts_part_depth_h", (void**)&parr->_part_depth_h, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_depth_h)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_depth_h, 0, nr_parts * sizeof(struct part_depth_h));

  if (swift_memalign("parts_part_time_bin", (void**)&parr->_part_time_bin, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_time_bin)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_time_bin, 0, nr_parts * sizeof(struct part_time_bin));

  if (swift_memalign("parts_part_limiter_data", (void**)&parr->_part_limiter_data, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_limiter_data)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_limiter_data, 0, nr_parts * sizeof(struct part_limiter_data));

  if (swift_memalign("parts_part_ti_drift", (void**)&parr->_part_ti_drift, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_ti_drift)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_ti_drift, 0, nr_parts * sizeof(struct part_ti_drift));

  if (swift_memalign("parts_part_ti_kick", (void**)&parr->_part_ti_kick, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_ti_kick)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_ti_kick, 0, nr_parts * sizeof(struct part_ti_kick));

  if (swift_memalign("parts_part_debugging", (void**)&parr->_part_debugging, SWIFT_PART_ALIGNMENT, nr_parts * sizeof(struct part_debugging)) != 0)
    error("Error while allocating memory for SPH particles");

  memset(parr->_part_debugging, 0, nr_parts * sizeof(struct part_debugging));


#ifdef SWIFT_DEBUG_CHECKS
  parr->nr_parts = nr_parts;
#endif

#ifdef SWIFT_DEBUG_CHECKS
  /* Give all particles a unique debugging ID which will be used to verify that
   * we're accessing the correct split struct. Note: ID = 0 is forbidden! */
  for (long long i = 1; i <= nr_parts; i++) {

    parr->_part[i-1]._accessor_id = i;
    parr->_part_id[i-1]._accessor_id = i;
    parr->_part_gpart[i-1]._accessor_id = i;
    parr->_part_x[i-1]._accessor_id = i;
    parr->_part_v[i-1]._accessor_id = i;
    parr->_part_a_hydro[i-1]._accessor_id = i;
    parr->_part_mass[i-1]._accessor_id = i;
    parr->_part_h[i-1]._accessor_id = i;
    parr->_part_u[i-1]._accessor_id = i;
    parr->_part_u_dt[i-1]._accessor_id = i;
    parr->_part_rho[i-1]._accessor_id = i;
    parr->_part_div_v[i-1]._accessor_id = i;
    parr->_part_div_v_dt[i-1]._accessor_id = i;
    parr->_part_div_v_previous_step[i-1]._accessor_id = i;
    parr->_part_alpha_av[i-1]._accessor_id = i;
    parr->_part_v_sig[i-1]._accessor_id = i;
    parr->_part_laplace_u[i-1]._accessor_id = i;
    parr->_part_alpha_diff[i-1]._accessor_id = i;
    parr->_part_density_force1[i-1]._accessor_id = i;
    parr->_part_density_force2[i-1]._accessor_id = i;
    parr->_part_density_force3[i-1]._accessor_id = i;
    parr->_part_density_force4[i-1]._accessor_id = i;
    parr->_part_additional_structs[i-1]._accessor_id = i;
    parr->_part_rt_time_data[i-1]._accessor_id = i;
    parr->_part_depth_h[i-1]._accessor_id = i;
    parr->_part_time_bin[i-1]._accessor_id = i;
    parr->_part_limiter_data[i-1]._accessor_id = i;
    parr->_part_ti_drift[i-1]._accessor_id = i;
    parr->_part_ti_kick[i-1]._accessor_id = i;
    parr->_part_debugging[i-1]._accessor_id = i;
  }
#endif
  /* We're done. Print out some information to screen */
  size_t total = 0;
  total+=sizeof(struct part);
  total+=sizeof(struct part_id);
  total+=sizeof(struct part_gpart);
  total+=sizeof(struct part_x);
  total+=sizeof(struct part_v);
  total+=sizeof(struct part_a_hydro);
  total+=sizeof(struct part_mass);
  total+=sizeof(struct part_h);
  total+=sizeof(struct part_u);
  total+=sizeof(struct part_u_dt);
  total+=sizeof(struct part_rho);
  total+=sizeof(struct part_div_v);
  total+=sizeof(struct part_div_v_dt);
  total+=sizeof(struct part_div_v_previous_step);
  total+=sizeof(struct part_alpha_av);
  total+=sizeof(struct part_v_sig);
  total+=sizeof(struct part_laplace_u);
  total+=sizeof(struct part_alpha_diff);
  total+=sizeof(struct part_density_force1);
  total+=sizeof(struct part_density_force2);
  total+=sizeof(struct part_density_force3);
  total+=sizeof(struct part_density_force4);
  total+=sizeof(struct part_additional_structs);
  total+=sizeof(struct part_rt_time_data);
  total+=sizeof(struct part_depth_h);
  total+=sizeof(struct part_time_bin);
  total+=sizeof(struct part_limiter_data);
  total+=sizeof(struct part_ti_drift);
  total+=sizeof(struct part_ti_kick);
  total+=sizeof(struct part_debugging);

  message("total size of a particle is %lu bytes", total);
  message("size of alloc'd parts is %.3g Mb", (nr_parts * total) / (1024. * 1024.));
}

/**
 * @brief Free the bytes from their prison of labour.
 */
static __attribute__((always_inline)) INLINE void clear_parts(struct hydro_part_arrays* parr) {

  free(parr->_part);
  free(parr->_part_id);
  free(parr->_part_gpart);
  free(parr->_part_x);
  free(parr->_part_v);
  free(parr->_part_a_hydro);
  free(parr->_part_mass);
  free(parr->_part_h);
  free(parr->_part_u);
  free(parr->_part_u_dt);
  free(parr->_part_rho);
  free(parr->_part_div_v);
  free(parr->_part_div_v_dt);
  free(parr->_part_div_v_previous_step);
  free(parr->_part_alpha_av);
  free(parr->_part_v_sig);
  free(parr->_part_laplace_u);
  free(parr->_part_alpha_diff);
  free(parr->_part_density_force1);
  free(parr->_part_density_force2);
  free(parr->_part_density_force3);
  free(parr->_part_density_force4);
  free(parr->_part_additional_structs);
  free(parr->_part_rt_time_data);
  free(parr->_part_depth_h);
  free(parr->_part_time_bin);
  free(parr->_part_limiter_data);
  free(parr->_part_ti_drift);
  free(parr->_part_ti_kick);
  free(parr->_part_debugging);
}

/**
 * @brief Initialise a hydro_part_arrays struct `dest` as an offset of a different
 * hydro_part_arrays struct `src`. Intended to initilise cell particle array data
 * as offsets to the global particle array.
 */
__attribute__((always_inline)) INLINE static void part_arrays_set_pointer_offset(
  struct hydro_part_arrays* dest, const struct hydro_part_arrays* src, ptrdiff_t offset
  ){


  dest->_part = &src->_part[offset];
  dest->_part_id = &src->_part_id[offset];
  dest->_part_gpart = &src->_part_gpart[offset];
  dest->_part_x = &src->_part_x[offset];
  dest->_part_v = &src->_part_v[offset];
  dest->_part_a_hydro = &src->_part_a_hydro[offset];
  dest->_part_mass = &src->_part_mass[offset];
  dest->_part_h = &src->_part_h[offset];
  dest->_part_u = &src->_part_u[offset];
  dest->_part_u_dt = &src->_part_u_dt[offset];
  dest->_part_rho = &src->_part_rho[offset];
  dest->_part_div_v = &src->_part_div_v[offset];
  dest->_part_div_v_dt = &src->_part_div_v_dt[offset];
  dest->_part_div_v_previous_step = &src->_part_div_v_previous_step[offset];
  dest->_part_alpha_av = &src->_part_alpha_av[offset];
  dest->_part_v_sig = &src->_part_v_sig[offset];
  dest->_part_laplace_u = &src->_part_laplace_u[offset];
  dest->_part_alpha_diff = &src->_part_alpha_diff[offset];
  dest->_part_density_force1 = &src->_part_density_force1[offset];
  dest->_part_density_force2 = &src->_part_density_force2[offset];
  dest->_part_density_force3 = &src->_part_density_force3[offset];
  dest->_part_density_force4 = &src->_part_density_force4[offset];
  dest->_part_additional_structs = &src->_part_additional_structs[offset];
  dest->_part_rt_time_data = &src->_part_rt_time_data[offset];
  dest->_part_depth_h = &src->_part_depth_h[offset];
  dest->_part_time_bin = &src->_part_time_bin[offset];
  dest->_part_limiter_data = &src->_part_limiter_data[offset];
  dest->_part_ti_drift = &src->_part_ti_drift[offset];
  dest->_part_ti_kick = &src->_part_ti_kick[offset];
  dest->_part_debugging = &src->_part_debugging[offset];
}


